import { useEffect, useMemo, useState, type FormEvent } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { Check, ImagePlus, KeyRound, Save, Trash2 } from "lucide-react";
import { PROPERTY_TYPES, SITE, TEAM } from "@/lib/site";
import type { Property, PropertyType, PropertyTransaction } from "@/lib/properties";
import { deleteProperty, listAdminProperties, saveProperty } from "@/lib/properties";
import { toast } from "sonner";
import { formatToman } from "@/lib/money";

export const Route = createFileRoute("/admin")({ component: AdminPropertiesPage, head: () => ({ meta: [{ title: `مدیریت فایل‌ها | ${SITE.nameFa}` }, { name: "robots", content: "noindex, nofollow" }] }) });
type FormState = {
  id?: string; adminKey: string; title: string; transactionType: PropertyTransaction; propertyType: PropertyType; neighborhood: string; address: string; areaM2: string; bedrooms: string; bathrooms: string; floor: string; totalFloors: string; builtYear: string; parking: boolean; elevator: boolean; storage: boolean; price: string; deposit: string; rent: string; description: string; features: string; images: string; contactName: string; contactPhone: string; status: "draft" | "published" | "archived"; featured: boolean;
};
const emptyForm = (adminKey = ""): FormState => ({ adminKey, title: "", transactionType: "sell", propertyType: "apartment", neighborhood: "", address: "", areaM2: "", bedrooms: "2", bathrooms: "1", floor: "", totalFloors: "", builtYear: "", parking: true, elevator: true, storage: false, price: "", deposit: "", rent: "", description: "", features: "نورگیر\nبازسازی‌شده", images: "", contactName: TEAM[0]?.name ?? "مشاور هیرمند", contactPhone: TEAM[0]?.phone ?? SITE.phone.mobile, status: "published", featured: false });
function numberOrNull(raw: string) { const digits = raw.replace(/[۰-۹]/g, (d) => String("۰۱۲۳۴۵۶۷۸۹".indexOf(d))); const value = digits.trim() ? Number(digits) : null; return value !== null && Number.isFinite(value) ? value : null; }
function splitLines(raw: string) { return raw.split(/[\n,]/).map((item) => item.trim()).filter(Boolean); }
function moneyLabel(raw: string | null) { if (!raw) return ""; const n = Number(raw); return Number.isFinite(n) ? `${formatToman(n)} تومان` : raw; }
function AdminPropertiesPage() {
  const [adminKey, setAdminKey] = useState(""); const [properties, setProperties] = useState<Property[]>([]); const [form, setForm] = useState<FormState>(emptyForm()); const [loading, setLoading] = useState(false); const [loadingList, setLoadingList] = useState(false);
  useEffect(() => { try { const stored = sessionStorage.getItem("hirmand-admin-key") ?? ""; if (stored) { setAdminKey(stored); setForm((prev) => ({ ...prev, adminKey: stored })); } } catch {} }, []);
  async function refresh(key = adminKey) { if (!key) return; setLoadingList(true); try { setProperties(await listAdminProperties({ data: { adminKey: key } })); } catch (error) { toast.error(error instanceof Error ? error.message : "دسترسی مدیر تأیید نشد."); } finally { setLoadingList(false); } }
  const update = <K extends keyof FormState>(key: K, value: FormState[K]) => setForm((prev) => ({ ...prev, [key]: value }));
  async function save(event: FormEvent) { event.preventDefault(); setLoading(true); try {
    if (!form.adminKey.trim()) throw new Error("کلید مدیریت را وارد کنید.");
    const result = await saveProperty({ data: { adminKey: form.adminKey, id: form.id, title: form.title, transactionType: form.transactionType, propertyType: form.propertyType, neighborhood: form.neighborhood, address: form.address, areaM2: numberOrNull(form.areaM2), bedrooms: numberOrNull(form.bedrooms), bathrooms: numberOrNull(form.bathrooms), floor: numberOrNull(form.floor), totalFloors: numberOrNull(form.totalFloors), builtYear: numberOrNull(form.builtYear), parking: form.parking, elevator: form.elevator, storage: form.storage, price: form.price, deposit: form.deposit, rent: form.rent, description: form.description, features: splitLines(form.features), images: splitLines(form.images), contactName: form.contactName, contactPhone: form.contactPhone, status: form.status, featured: form.featured } });
    sessionStorage.setItem("hirmand-admin-key", form.adminKey); setAdminKey(form.adminKey); setProperties((prev) => prev.some((item) => item.id === result.id) ? prev.map((item) => item.id === result.id ? result : item) : [result, ...prev]); setForm(emptyForm(form.adminKey)); toast.success("فایل ملک با موفقیت ذخیره شد.");
  } catch (error) { toast.error(error instanceof Error ? error.message : "ذخیره فایل انجام نشد."); } finally { setLoading(false); } }
  function edit(property: Property) { setForm({ id: property.id, adminKey, title: property.title, transactionType: property.transactionType, propertyType: property.propertyType, neighborhood: property.neighborhood, address: property.address ?? "", areaM2: property.areaM2?.toString() ?? "", bedrooms: property.bedrooms?.toString() ?? "", bathrooms: property.bathrooms?.toString() ?? "", floor: property.floor?.toString() ?? "", totalFloors: property.totalFloors?.toString() ?? "", builtYear: property.builtYear?.toString() ?? "", parking: property.parking, elevator: property.elevator, storage: property.storage, price: property.price ?? "", deposit: property.deposit ?? "", rent: property.rent ?? "", description: property.description, features: property.features.join("\n"), images: property.images.join("\n"), contactName: property.contactName, contactPhone: property.contactPhone, status: property.status, featured: property.featured }); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function remove(property: Property) { if (!window.confirm(`فایل «${property.title}» حذف شود؟`)) return; try { await deleteProperty({ data: { adminKey, id: property.id } }); setProperties((prev) => prev.filter((item) => item.id !== property.id)); toast.success("فایل حذف شد."); } catch (error) { toast.error(error instanceof Error ? error.message : "حذف فایل انجام نشد."); } }
  const publishedCount = useMemo(() => properties.filter((item) => item.status === "published").length, [properties]);
  return <main className="admin-shell"><header className="admin-header"><div><span className="kicker">مدیریت فایل‌ها</span><h1>افزودن و مدیریت ملک‌های هیرمند</h1><p>این بخش خصوصی است؛ کلید مدیریت را فقط نزد خودتان نگه دارید.</p></div><Link to="/" className="btn-ghost">نمایش سایت</Link></header>
    <section className="admin-key-panel"><div><KeyRound size={20} /><div><strong>کلید مدیریت</strong><small>از متغیر سرور HIRMAND_ADMIN_KEY استفاده می‌شود؛ این کلید داخل کد قرار نگرفته است.</small></div></div><div className="admin-key-row"><input type="password" value={adminKey} onChange={(event) => { setAdminKey(event.target.value); setForm((prev) => ({ ...prev, adminKey: event.target.value })); }} placeholder="کلید مدیریت" autoComplete="off"/><button type="button" className="btn-gold" onClick={() => refresh()} disabled={!adminKey || loadingList}>{loadingList ? "..." : "ورود به مدیریت"}</button></div></section>
    <form className="admin-form" onSubmit={save}><div className="admin-form-head"><div><span className="kicker">{form.id ? "ویرایش فایل" : "فایل جدید"}</span><h2>{form.id ? "ویرایش مشخصات ملک" : "ثبت یک ملک جدید"}</h2></div>{form.id ? <button type="button" className="btn-ghost" onClick={() => setForm(emptyForm(adminKey))}>لغو و فایل جدید</button> : null}</div>
      <div className="admin-form-grid">
        <label className="field field-span"><span>عنوان فایل</span><input value={form.title} onChange={(e) => update("title", e.target.value)} placeholder="مثلاً آپارتمان ۱۴۰ متری مرداویج" required /></label>
        <label className="field"><span>نوع معامله</span><select value={form.transactionType} onChange={(e) => update("transactionType", e.target.value as PropertyTransaction)}><option value="sell">فروش</option><option value="rent">اجاره</option><option value="mortgage">رهن</option></select></label>
        <label className="field"><span>نوع ملک</span><select value={form.propertyType} onChange={(e) => update("propertyType", e.target.value as PropertyType)}>{PROPERTY_TYPES.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}<option value="land">زمین</option><option value="commercial">تجاری</option></select></label>
        <label className="field"><span>محله</span><input value={form.neighborhood} onChange={(e) => update("neighborhood", e.target.value)} placeholder="مثلاً مرداویج" required /></label>
        <label className="field"><span>آدرس / توضیح موقعیت</span><input value={form.address} onChange={(e) => update("address", e.target.value)} placeholder="اختیاری" /></label>
        <label className="field"><span>متراژ</span><input inputMode="numeric" value={form.areaM2} onChange={(e) => update("areaM2", e.target.value)} placeholder="۱۴۰" /></label>
        <label className="field"><span>تعداد خواب</span><input inputMode="numeric" value={form.bedrooms} onChange={(e) => update("bedrooms", e.target.value)} /></label>
        <label className="field"><span>حمام</span><input inputMode="numeric" value={form.bathrooms} onChange={(e) => update("bathrooms", e.target.value)} /></label>
        <label className="field"><span>طبقه</span><input inputMode="numeric" value={form.floor} onChange={(e) => update("floor", e.target.value)} /></label>
        <label className="field"><span>تعداد طبقات</span><input inputMode="numeric" value={form.totalFloors} onChange={(e) => update("totalFloors", e.target.value)} /></label>
        <label className="field"><span>سال ساخت</span><input inputMode="numeric" value={form.builtYear} onChange={(e) => update("builtYear", e.target.value)} /></label>
        <div className="admin-checks field-span"><label><input type="checkbox" checked={form.parking} onChange={(e) => update("parking", e.target.checked)} /> پارکینگ</label><label><input type="checkbox" checked={form.elevator} onChange={(e) => update("elevator", e.target.checked)} /> آسانسور</label><label><input type="checkbox" checked={form.storage} onChange={(e) => update("storage", e.target.checked)} /> انباری</label><label><input type="checkbox" checked={form.featured} onChange={(e) => update("featured", e.target.checked)} /> فایل ویژه</label></div>
        <label className="field"><span>قیمت فروش</span><input inputMode="numeric" value={form.price} onChange={(e) => update("price", e.target.value)} placeholder="تومان" /></label><label className="field"><span>رهن</span><input inputMode="numeric" value={form.deposit} onChange={(e) => update("deposit", e.target.value)} placeholder="تومان" /></label><label className="field"><span>اجاره</span><input inputMode="numeric" value={form.rent} onChange={(e) => update("rent", e.target.value)} placeholder="تومان" /></label><label className="field"><span>وضعیت نمایش</span><select value={form.status} onChange={(e) => update("status", e.target.value as FormState["status"])}><option value="published">منتشر شود</option><option value="draft">پیش‌نویس</option><option value="archived">بایگانی</option></select></label>
        <label className="field field-span"><span>توضیحات</span><textarea rows={6} value={form.description} onChange={(e) => update("description", e.target.value)} placeholder="توضیحات کامل ملک..." required /></label>
        <label className="field"><span>ویژگی‌ها</span><textarea rows={6} value={form.features} onChange={(e) => update("features", e.target.value)} placeholder={"نورگیر\nبازسازی‌شده\nلابی"} /><small>هر ویژگی در یک خط</small></label>
        <label className="field"><span>آدرس تصاویر</span><textarea rows={6} value={form.images} onChange={(e) => update("images", e.target.value)} placeholder={"https://...\nhttps://..."} /><small>هر لینک تصویر در یک خط؛ تا ۱۲ تصویر</small></label>
        <label className="field"><span>نام مشاور</span><input value={form.contactName} onChange={(e) => update("contactName", e.target.value)} required /></label><label className="field"><span>شماره مشاور</span><input dir="ltr" value={form.contactPhone} onChange={(e) => update("contactPhone", e.target.value)} required /></label>
      </div>
      <div className="admin-form-actions"><button type="submit" className="btn-gold" disabled={loading}>{loading ? "در حال ذخیره..." : <><Save size={17} /> {form.id ? "ذخیره تغییرات" : "انتشار فایل"}</>}</button><span className="admin-hint"><ImagePlus size={15} /> فعلاً تصاویر با URL ثبت می‌شوند؛ مرحله بعد می‌توانیم آپلود مستقیم هم اضافه کنیم.</span></div>
    </form>
    <section className="admin-list"><div className="admin-list-head"><div><span className="kicker">فایل‌ها</span><h2>{publishedCount.toLocaleString("fa-IR")} فایل منتشرشده</h2></div><button type="button" className="btn-ghost" onClick={() => refresh()} disabled={!adminKey || loadingList}>به‌روزرسانی</button></div>
      <div className="admin-list-grid">{properties.map((property) => <article key={property.id} className="admin-property-row"><div className="admin-property-thumb"><img src={property.images[0] || "/images/type-apartment.jpg"} alt="" loading="lazy" /></div><div className="admin-property-info"><div className="admin-property-tags"><span>{property.status}</span>{property.featured ? <span>ویژه</span> : null}</div><h3>{property.title}</h3><p>{property.neighborhood} {property.areaM2 ? `• ${property.areaM2.toLocaleString("fa-IR")} متر` : ""}</p>{property.price ? <strong>{moneyLabel(property.price)}</strong> : null}</div><div className="admin-property-actions"><button type="button" className="btn-ghost" onClick={() => edit(property)}><Check size={15} /> ویرایش</button><button type="button" className="danger-btn" onClick={() => remove(property)}><Trash2 size={15} /> حذف</button></div></article>)}</div>
    </section><footer className="admin-footer"><Link to="/" className="text-link">بازگشت به سایت</Link></footer></main>;
}
