create table if not exists site_redirects (
  id bigint generated by default as identity primary key,
  source_path text not null unique,
  target_path text not null,
  status_code smallint not null default 301 check (status_code in (301,302,307,308)),
  active boolean not null default true,
  hit_count bigint not null default 0,
  last_hit_at timestamptz,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp
);

create index if not exists site_redirects_active_source_idx
  on site_redirects (source_path)
  where active = true;

create table if not exists site_404_logs (
  id bigint generated by default as identity primary key,
  path text not null unique,
  hit_count bigint not null default 1,
  referrer text not null default '',
  user_agent text not null default '',
  first_seen_at timestamptz not null default current_timestamp,
  last_seen_at timestamptz not null default current_timestamp
);

create index if not exists site_404_logs_recent_idx
  on site_404_logs (last_seen_at desc);
