import { useEffect, useMemo, useState } from "react";
import { Activity, CalendarDays, Camera, CheckCircle2, Clock3, MapPin, Phone, Plus, RefreshCw, ShieldAlert, Smartphone, UserRound, Users, XCircle } from "lucide-react";
import "@/admin-staff-operations.css";

type Staff={id:string;name:string;role:string};
type Device={id:string;deviceId:string;staffId:string;staffName:string;status:string;model:string;manufacturer:string;androidVersion:string;managementMode:string;lastSeenAt:string|null;lastSyncAt:string|null;lostMode:boolean;lostMessage:string};
type Task={id:string;staffId:string;staffName:string;title:string;description:string;status:string;priority:string;propertyId:string|null;customerId:string|null;dueAt:string|null};
type Visit={id:string;staffId:string;staffName:string;propertyId:string|null;title:string;address:string;targetLat:number|null;targetLng:number|null;radiusM:number;scheduledAt:string|null;status:string;arrivedAt:string|null;leftAt:string|null;notes:string};
type Contact={id:string;staffId:string;name:string;phone:string;type:string;notes:string;propertyId:string|null;nextFollowUpAt:string|null};
type Capture={id:string;staffId:string;staffName:string;deviceId:string;propertyId:string|null;visitId:string|null;category:string;caption:string;createdAt:string|null;fileName:string;mimeType:string;sizeBytes:number;streamUrl:string};
type Ops={success:boolean;staff:Staff[];devices:Device[];tasks:Task[];visits:Visit[];contacts:Contact[];attendance:Array<any>;captures:Capture[];health:Array<{deviceId:string;staffId:string;payload:any;observedAt:string|null}>;performance:Array<{staffId:string;staffName:string;role:string;tasksDone:number;visitsDone:number;callsDone:number;attendanceDays:number}>;stats:{calls24h:number;recordings24h:number}};

const faDate=(v:string|null)=>v?new Intl.DateTimeFormat("fa-IR",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Tehran"}).format(new Date(v)):"—";

async function api(action:string,payload:Record<string,unknown>={}){
  const r=await fetch("/api/admin/mobile-management/staff-operations"+(action==="get"?"":""),{
    method:action==="get"?"GET":"POST",credentials:"same-origin",cache:"no-store",
    headers:action==="get"?undefined:{"content-type":"application/json"},
    body:action==="get"?undefined:JSON.stringify(payload),
  });
  const data=await r.json().catch(()=>null);
  if(!r.ok||!data?.success) throw new Error(data?.message||data?.statusMessage||"درخواست انجام نشد.");
  return data;
}

export function AdminStaffOperationsPage(){
  const [data,setData]=useState<Ops|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const [tab,setTab]=useState<"overview"|"tasks"|"visits"|"crm"|"security">("overview");
  const [form,setForm]=useState({staffId:"",title:"",description:"",priority:"normal",dueAt:"",propertyId:"",customerId:"",deviceId:"",address:"",targetLat:"",targetLng:"",radiusM:"120",scheduledAt:"",name:"",phone:"",type:"customer",notes:"",nextFollowUpAt:""});
  const load=async()=>{setLoading(true);setError("");try{setData(await api("get"))}catch(e){setError(e instanceof Error?e.message:"خطا")}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  const staffOptions=data?.staff??[];
  useEffect(()=>{if(!form.staffId&&staffOptions[0])setForm(v=>({...v,staffId:staffOptions[0].id}))},[staffOptions.length,form.staffId]);
  const activeTasks=useMemo(()=>data?.tasks.filter(x=>x.status!=="done")??[],[data]);
  const openVisits=useMemo(()=>data?.visits.filter(x=>x.status!=="completed")??[],[data]);

  async function createTask(){if(!form.staffId||!form.title.trim())return;await api("post",{action:"create_task",...form});setForm(v=>({...v,title:"",description:"",dueAt:"",propertyId:"",customerId:""}));await load();}
  async function createVisit(){if(!form.staffId||!form.title.trim())return;await api("post",{action:"create_visit",staffId:form.staffId,title:form.title,propertyId:form.propertyId,address:form.address,targetLat:form.targetLat,targetLng:form.targetLng,radiusM:form.radiusM,scheduledAt:form.scheduledAt,notes:form.notes});setForm(v=>({...v,title:"",propertyId:"",address:"",targetLat:"",targetLng:"",scheduledAt:"",notes:""}));await load();}
  async function createContact(){if(!form.staffId||!form.name.trim())return;await api("post",{action:"create_contact",staffId:form.staffId,name:form.name,phone:form.phone,type:form.type,notes:form.notes,propertyId:form.propertyId,nextFollowUpAt:form.nextFollowUpAt});setForm(v=>({...v,name:"",phone:"",notes:"",propertyId:"",nextFollowUpAt:""}));await load();}
  async function taskStatus(id:string,status:string){await api("post",{action:"update_task",id,status});await load();}
  async function deviceLost(device:Device){await api("post",{action:device.lostMode?"device_lost_clear":"device_lost",deviceId:device.deviceId,message:"این دستگاه توسط مدیریت هیرمند به‌عنوان مفقود علامت‌گذاری شده است. لطفاً با مدیریت تماس بگیرید."});await load();}
  const deviceStats=data?.devices.reduce((a,d)=>{a[d.status]=(a[d.status]||0)+1;return a},{} as Record<string,number>)??{};
  return <main className="admin-staff-ops-page"><div className="admin-staff-ops-shell">
    <header className="admin-staff-ops-head"><div><span>Hirmand Staff · Operations Center</span><h1>مرکز عملیات کارکنان</h1><p>مدیریت مأموریت، بازدید ملک، CRM، حضور، دستگاه و گزارش عملکرد در اپ رسمی املاک هیرمند.</p></div><button className="ops-button" onClick={()=>void load()} disabled={loading}><RefreshCw size={16}/> بروزرسانی</button></header>
    <nav className="ops-tabs">{([["overview","نمای کلی"],["tasks","وظایف"],["visits","بازدید ملک"],["crm","CRM و مشتریان"],["security","امنیت و دستگاه"] ] as const).map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</nav>
    {error?<div className="ops-error">{error}</div>:null}
    {loading&&!data?<div className="ops-panel">در حال دریافت اطلاعات…</div>:null}
    {data&&tab==="overview"?<><section className="ops-kpis">
      <article><Activity/><span>دستگاه فعال</span><strong>{deviceStats.active??0}</strong></article><article><CheckCircle2/><span>وظایف باز</span><strong>{activeTasks.length}</strong></article>
      <article><MapPin/><span>بازدیدهای باز</span><strong>{openVisits.length}</strong></article><article><Phone/><span>تماس ۲۴ ساعت</span><strong>{data.stats.calls24h.toLocaleString("fa-IR")}</strong></article>
      <article><Camera/><span>ضبط/مدرک تصویری</span><strong>{data.captures.length.toLocaleString("fa-IR")}</strong></article><article><ShieldAlert/><span>دستگاه مفقود</span><strong>{data.devices.filter(d=>d.lostMode).length}</strong></article>
    </section><section className="ops-panel ops-performance"><div className="ops-panel-head"><h2>گزارش عملکرد ۳۰ روز اخیر</h2><span>به‌ازای هر کارمند</span></div><div className="ops-performance-grid">{data.performance.map(p=><article key={p.staffId}><strong>{p.staffName}</strong><small>{p.role}</small><span>وظیفه انجام‌شده: <b>{p.tasksDone.toLocaleString("fa-IR")}</b></span><span>بازدید تکمیل‌شده: <b>{p.visitsDone.toLocaleString("fa-IR")}</b></span><span>تماس ثبت‌شده: <b>{p.callsDone.toLocaleString("fa-IR")}</b></span><span>روز حضور: <b>{p.attendanceDays.toLocaleString("fa-IR")}</b></span></article>)}</div></section><section className="ops-grid"><article className="ops-panel"><div className="ops-panel-head"><h2>وظایف مهم</h2><button onClick={()=>setTab("tasks")}>همه</button></div>{activeTasks.slice(0,8).map(t=><div className="ops-row" key={t.id}><div><strong>{t.title}</strong><small>{t.staffName} · {t.priority} · {faDate(t.dueAt)}</small></div><button onClick={()=>void taskStatus(t.id,"done")}><CheckCircle2 size={15}/> انجام شد</button></div>)}{!activeTasks.length?<p className="ops-empty">وظیفه باز نداریم.</p>:null}</article>
      <article className="ops-panel"><div className="ops-panel-head"><h2>بازدیدهای پیش‌رو</h2><button onClick={()=>setTab("visits")}>همه</button></div>{openVisits.slice(0,8).map(v=><div className="ops-row" key={v.id}><div><strong>{v.title}</strong><small>{v.staffName} · {v.address||"بدون آدرس"} · {faDate(v.scheduledAt)}</small></div><span className="ops-pill">{v.status}</span></div>)}{!openVisits.length?<p className="ops-empty">بازدیدی ثبت نشده است.</p>:null}</article></section></>:null}
    {data&&tab==="tasks"?<section className="ops-grid"><article className="ops-panel"><h2>ساخت وظیفه برای کارمند</h2><div className="ops-form"><select value={form.staffId} onChange={e=>setForm(v=>({...v,staffId:e.target.value}))}>{staffOptions.map(s=><option value={s.id} key={s.id}>{s.name} · {s.role}</option>)}</select><input value={form.title} placeholder="عنوان وظیفه" onChange={e=>setForm(v=>({...v,title:e.target.value}))}/><textarea value={form.description} placeholder="شرح" onChange={e=>setForm(v=>({...v,description:e.target.value}))}/><select value={form.priority} onChange={e=>setForm(v=>({...v,priority:e.target.value}))}><option value="low">کم</option><option value="normal">عادی</option><option value="high">مهم</option><option value="urgent">فوری</option></select><input value={form.dueAt} type="datetime-local" onChange={e=>setForm(v=>({...v,dueAt:e.target.value}))}/><input value={form.propertyId} placeholder="شناسه فایل ملک (اختیاری)" onChange={e=>setForm(v=>({...v,propertyId:e.target.value}))}/><button className="ops-button primary" onClick={()=>void createTask()}><Plus size={15}/> ساخت وظیفه</button></div></article>
      <article className="ops-panel"><h2>وظایف موجود</h2>{data.tasks.map(t=><div className="ops-row" key={t.id}><div><strong>{t.title}</strong><small>{t.staffName} · {t.status} · {faDate(t.dueAt)}</small></div><div className="ops-actions">{t.status!=="done"?<button onClick={()=>void taskStatus(t.id,"done")}>انجام شد</button>:<XCircle size={15}/>}</div></div>)}</article></section>:null}
    {data&&tab==="visits"?<section className="ops-grid"><article className="ops-panel"><h2>ثبت مأموریت/بازدید</h2><p className="ops-hint">برای فعال شدن geofence، مختصات هدف و شعاع را وارد کنید.</p><div className="ops-form"><select value={form.staffId} onChange={e=>setForm(v=>({...v,staffId:e.target.value}))}>{staffOptions.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select><input value={form.title} placeholder="مثلاً بازدید فروش آپارتمان" onChange={e=>setForm(v=>({...v,title:e.target.value}))}/><input value={form.address} placeholder="آدرس" onChange={e=>setForm(v=>({...v,address:e.target.value}))}/><div className="ops-two"><input value={form.targetLat} placeholder="Latitude" inputMode="decimal" onChange={e=>setForm(v=>({...v,targetLat:e.target.value}))}/><input value={form.targetLng} placeholder="Longitude" inputMode="decimal" onChange={e=>setForm(v=>({...v,targetLng:e.target.value}))}/></div><div className="ops-two"><input value={form.radiusM} placeholder="شعاع متر" inputMode="numeric" onChange={e=>setForm(v=>({...v,radiusM:e.target.value}))}/><input value={form.scheduledAt} type="datetime-local" onChange={e=>setForm(v=>({...v,scheduledAt:e.target.value}))}/></div><textarea value={form.notes} placeholder="یادداشت بازدید" onChange={e=>setForm(v=>({...v,notes:e.target.value}))}/><button className="ops-button primary" onClick={()=>void createVisit()}><MapPin size={15}/> ثبت بازدید</button></div></article>
      <article className="ops-panel"><h2>بازدیدهای ثبت‌شده</h2>{data.visits.map(v=><div className="ops-row" key={v.id}><div><strong>{v.title}</strong><small>{v.staffName} · {v.status} · شعاع {v.radiusM.toLocaleString("fa-IR")} متر</small><small>{v.address}</small></div>{v.targetLat!=null?<span className="ops-pill">geofence</span>:<span className="ops-pill muted">بدون geofence</span>}</div>)}</article></section>:null}
    {data&&tab==="crm"?<section className="ops-grid"><article className="ops-panel"><h2>مخاطب CRM جدید</h2><div className="ops-form"><select value={form.staffId} onChange={e=>setForm(v=>({...v,staffId:e.target.value}))}>{staffOptions.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select><input value={form.name} placeholder="نام مشتری/مالک" onChange={e=>setForm(v=>({...v,name:e.target.value}))}/><input value={form.phone} placeholder="شماره تماس" inputMode="tel" onChange={e=>setForm(v=>({...v,phone:e.target.value}))}/><select value={form.type} onChange={e=>setForm(v=>({...v,type:e.target.value}))}><option value="customer">مشتری</option><option value="owner">مالک</option><option value="buyer">خریدار</option><option value="tenant">مستأجر</option><option value="builder">سازنده</option><option value="partner">همکار</option></select><input value={form.propertyId} placeholder="شناسه ملک مرتبط" onChange={e=>setForm(v=>({...v,propertyId:e.target.value}))}/><input value={form.nextFollowUpAt} type="datetime-local" onChange={e=>setForm(v=>({...v,nextFollowUpAt:e.target.value}))}/><textarea value={form.notes} placeholder="یادداشت CRM" onChange={e=>setForm(v=>({...v,notes:e.target.value}))}/><button className="ops-button primary" onClick={()=>void createContact()}><Users size={15}/> ثبت مخاطب</button></div></article>
      <article className="ops-panel"><h2>مخاطبان CRM</h2>{data.contacts.map(c=><div className="ops-row" key={c.id}><div><strong>{c.name}</strong><small>{c.phone||"بدون تلفن"} · {c.type} · مسئول: {data.staff.find(s=>s.id===c.staffId)?.name||"—"}</small><small>پیگیری بعدی: {faDate(c.nextFollowUpAt)}</small></div>{c.phone?<a className="ops-call" href={"tel:"+c.phone}><Phone size={15}/> تماس</a>:null}</div>)}</article></section>:null}
    {data&&tab==="security"?<section className="ops-grid"><article className="ops-panel"><h2>امنیت و سلامت دستگاه</h2>{data.devices.map(d=><div className="ops-device" key={d.deviceId}><div><strong>{d.staffName}</strong><small>{d.manufacturer} {d.model} · Android {d.androidVersion||"—"} · {d.managementMode}</small><small>آخرین اتصال: {faDate(d.lastSeenAt)}</small>{d.lostMode?<b className="danger-text">⚠ {d.lostMessage||"دستگاه مفقود علامت‌گذاری شده است."}</b>:null}{(()=>{const h=data.health.find(x=>x.deviceId===d.deviceId);const p=h?.payload||{};const battery=p.battery?.batteryPercent;const storage=p.storageAvailableBytes;const net=p.network?.connected;return <small className="ops-health-line">سلامت: {battery==null?"—":battery+"٪ باتری"} · {storage==null?"—":Math.round(Number(storage)/1048576).toLocaleString("fa-IR")+"MB آزاد"} · {net===true?"آنلاین":"آفلاین"}</small>})()}</div><button className={d.lostMode?"danger-btn":""} onClick={()=>void deviceLost(d)}>{d.lostMode?"لغو حالت مفقودی":"علامت‌گذاری مفقود"}</button></div>)}</article>
      <article className="ops-panel"><h2>آخرین تصاویر املاک</h2><div className="ops-captures">{data.captures.slice(0,18).map(c=><a className="ops-capture" href={c.streamUrl} target="_blank" rel="noreferrer" key={c.id}><img src={c.streamUrl} alt={c.category}/><span>{c.staffName} · {c.category}</span><small>{faDate(c.createdAt)}</small></a>)}</div></article></section>:null}
  </div></main>;
}
