import { useEffect, useMemo, useState } from "react";
import { Activity, BarChart3, CalendarCheck2, Camera, CheckCircle2, Link2, MapPin, Phone, Plus, RefreshCw, ShieldAlert, UserRound, Users, Zap } from "lucide-react";
import "@/admin-staff-operations.css";

type Staff={id:string;name:string;role:string};
type Device={id:string;deviceId:string;staffId:string;staffName:string;status:string;model:string;manufacturer:string;androidVersion:string;managementMode:string;lastSeenAt:string|null;lastSyncAt:string|null;lostMode:boolean;lostMessage:string};
type Task={id:string;staffId:string;staffName:string;title:string;description:string;status:string;priority:string;propertyId:string|null;customerId:string|null;dueAt:string|null;automation:boolean};
type Visit={id:string;staffId:string;staffName:string;propertyId:string|null;title:string;address:string;targetLat:number|null;targetLng:number|null;radiusM:number;scheduledAt:string|null;status:string;arrivedAt:string|null;leftAt:string|null;notes:string};
type Property={id:string;title:string;slug:string;status:string;transactionType:string;propertyType:string;neighborhood:string;areaM2:number|null;bedrooms:number|null;price:number|null;deposit:number|null;rent:number|null};
type Contact={id:string;staffId:string;staffName:string;name:string;phone:string;type:string;notes:string;leadId:string|null;leadStatus:string|null;leadDeal:string|null;leadNeighborhood:string|null;leadScore:number;leadScoreBand:string;propertyId:string|null;nextFollowUpAt:string|null;linkedProperties:Property[];recommendedProperties:Array<any>};
type Interaction={id:string;contactId:string;staffId:string;staffName:string;kind:string;note:string;createdAt:string|null};
type Lead={id:string;name:string;phone:string;status:string;source:string;consultant:string;deal:string;neighborhood:string;propertyId:string|null;followUpAt:string|null;leadScore:number;leadScoreBand:string;matchCount:number};
type Capture={id:string;staffId:string;staffName:string;deviceId:string;propertyId:string|null;visitId:string|null;category:string;caption:string;createdAt:string|null;fileName:string;mimeType:string;sizeBytes:number;streamUrl:string};
type Health={deviceId:string;staffId:string;payload:any;observedAt:string|null};
type Daily={staffId:string;staffName:string;role:string;tasksToday:number;tasksDoneToday:number;visitsToday:number;visitsDoneToday:number;callsToday:number;followUpsDue:number;capturesToday:number};
type Performance={staffId:string;staffName:string;role:string;tasksDone:number;visitsDone:number;callsDone:number;attendanceDays:number;interactions:number;overdueFollowUps:number;score:number};
type Ops={success:boolean;staff:Staff[];devices:Device[];tasks:Task[];visits:Visit[];contacts:Contact[];interactions:Interaction[];attendance:any[];captures:Capture[];health:Health[];daily:Daily[];performance:Performance[];leads:Lead[];properties:Property[];pipeline:Array<{status:string;count:number}>;analytics:{total:number;contacted:number;reachedVisit:number;reachedContract:number;closed:number;avgHoursToContact:number;avgActiveScore:number;contactRate:number;visitRate:number;contractRate:number;closeRate:number};automation:{created:number;overdue:number};stats:{calls24h:number;recordings24h:number}};

const faDate=(v:string|null)=>v?new Intl.DateTimeFormat("fa-IR",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Tehran"}).format(new Date(v)):"—";
const money=(v:number|null)=>v==null?"—":new Intl.NumberFormat("fa-IR").format(v)+" تومان";
const statusLabel=(v:string)=>({new:"جدید",contacted:"تماس گرفته شد",follow_up:"پیگیری",visited:"بازدید",contract:"قرارداد",closed:"بسته‌شده",spam:"اسپم"} as Record<string,string>)[v]??v;

async function api(method:"get"|"post",payload:Record<string,unknown>={}){
  const r=await fetch("/api/admin/mobile-management/staff-operations",{method:method==="get"?"GET":"POST",credentials:"same-origin",cache:"no-store",headers:method==="get"?undefined:{"content-type":"application/json"},body:method==="get"?undefined:JSON.stringify(payload)});
  const data=await r.json().catch(()=>null);
  if(!r.ok||!data?.success)throw new Error(data?.statusMessage||data?.message||"درخواست انجام نشد.");
  return data as Ops & {count?:number;created?:number;overdue?:number};
}

export function AdminStaffOperationsPage(){
  const [data,setData]=useState<Ops|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const [tab,setTab]=useState<"overview"|"pipeline"|"tasks"|"visits"|"crm"|"security">("overview");
  const [busy,setBusy]=useState(false);
  const [staffId,setStaffId]=useState("");
  const [task,setTask]=useState({title:"",description:"",priority:"normal",dueAt:"",propertyId:"",customerId:""});
  const [visit,setVisit]=useState({title:"",propertyId:"",address:"",targetLat:"",targetLng:"",radiusM:"120",scheduledAt:"",notes:""});
  const [contact,setContact]=useState({name:"",phone:"",type:"customer",notes:"",leadId:"",nextFollowUpAt:"",relationType:"interested"});
  const [contactProperties,setContactProperties]=useState<string[]>([]);
  const [linkContactId,setLinkContactId]=useState("");
  const [linkLeadId,setLinkLeadId]=useState("");
  const [linkPropertyIds,setLinkPropertyIds]=useState<string[]>([]);
  const load=async()=>{setLoading(true);setError("");try{setData(await api("get"))}catch(e){setError(e instanceof Error?e.message:"خطا")}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  const staffOptions=data?.staff??[];
  useEffect(()=>{if(!staffId&&staffOptions[0])setStaffId(staffOptions[0].id)},[staffId,staffOptions.length]);
  const activeTasks=useMemo(()=>data?.tasks.filter(x=>!["done","cancelled"].includes(x.status))??[],[data]);
  const openVisits=useMemo(()=>data?.visits.filter(x=>!["completed","cancelled"].includes(x.status))??[],[data]);
  const todayTotals=useMemo(()=>{const rows=data?.daily??[];return rows.reduce((a,r)=>({tasks:a.tasks+r.tasksToday,tasksDone:a.tasksDone+r.tasksDoneToday,visits:a.visits+r.visitsToday,visitsDone:a.visitsDone+r.visitsDoneToday,calls:a.calls+r.callsToday,followups:a.followups+r.followUpsDue,captures:a.captures+r.capturesToday}),{tasks:0,tasksDone:0,visits:0,visitsDone:0,calls:0,followups:0,captures:0})},[data]);
  const interactionMap=useMemo(()=>{const m=new Map<string,Interaction[]>();for(const i of data?.interactions??[]){const a=m.get(i.contactId)??[];a.push(i);m.set(i.contactId,a)}return m},[data]);

  async function run(action:string){setBusy(true);try{const result=await api("post",{action});await load();alert(action==="generate_followups"?String(result.created??0)+" پیگیری خودکار ساخته/به‌روزرسانی شد.":String(result.count??0)+" گزارش روزانه ثبت شد.")}catch(e){setError(e instanceof Error?e.message:"عملیات انجام نشد.")}finally{setBusy(false)}}
  async function createTask(){if(!staffId||!task.title.trim())return;setBusy(true);try{await api("post",{action:"create_task",staffId,...task});setTask({title:"",description:"",priority:"normal",dueAt:"",propertyId:"",customerId:""});await load()}catch(e){setError(e instanceof Error?e.message:"ثبت وظیفه انجام نشد.")}finally{setBusy(false)}}
  async function createVisit(){if(!staffId||!visit.title.trim())return;setBusy(true);try{await api("post",{action:"create_visit",staffId,...visit});setVisit({title:"",propertyId:"",address:"",targetLat:"",targetLng:"",radiusM:"120",scheduledAt:"",notes:""});await load()}catch(e){setError(e instanceof Error?e.message:"ثبت بازدید انجام نشد.")}finally{setBusy(false)}}
  async function createContact(){if(!staffId||!contact.name.trim())return;setBusy(true);try{await api("post",{action:"create_contact",staffId,...contact,propertyIds:contactProperties});setContact({name:"",phone:"",type:"customer",notes:"",leadId:"",nextFollowUpAt:"",relationType:"interested"});setContactProperties([]);await load()}catch(e){setError(e instanceof Error?e.message:"ثبت CRM انجام نشد.")}finally{setBusy(false)}}
  async function linkContact(){if(!linkContactId)return;setBusy(true);try{await api("post",{action:"link_contact",contactId:linkContactId,leadId:linkLeadId,propertyIds:linkPropertyIds,replaceProperties:true});setLinkContactId("");setLinkLeadId("");setLinkPropertyIds([]);await load()}catch(e){setError(e instanceof Error?e.message:"اتصال CRM انجام نشد.")}finally{setBusy(false)}}
  async function taskStatus(id:string,status:string){setBusy(true);try{await api("post",{action:"update_task",id,status});await load()}catch(e){setError(e instanceof Error?e.message:"تغییر وظیفه انجام نشد.")}finally{setBusy(false)}}
  async function deviceLost(d:Device){setBusy(true);try{await api("post",{action:d.lostMode?"device_lost_clear":"device_lost",deviceId:d.deviceId,message:"این دستگاه توسط مدیریت هیرمند به‌عنوان مفقود علامت‌گذاری شده است. لطفاً با مدیریت تماس بگیرید."});await load()}catch(e){setError(e instanceof Error?e.message:"عملیات دستگاه انجام نشد.")}finally{setBusy(false)}}
  async function leadStatus(id:string,status:string){setBusy(true);try{await api("post",{action:"lead_status",id,status});await load()}catch(e){setError(e instanceof Error?e.message:"تغییر مرحله لید انجام نشد.")}finally{setBusy(false)}}

  return <main className="admin-staff-ops-page"><div className="admin-staff-ops-shell">
    <header className="admin-staff-ops-head"><div><span>HIRMAND STAFF · OPERATIONS</span><h1>مرکز عملیات کارکنان</h1><p>CRM یکپارچه، برنامه روزانه، پیگیری خودکار، گزارش عملکرد، بازدید و همگام‌سازی اپ رسمی کارکنان.</p></div><button className="ops-button" onClick={()=>void load()} disabled={loading||busy}><RefreshCw size={16}/> بروزرسانی</button></header>
    <nav className="ops-tabs">{([["overview","داشبورد روزانه"],["pipeline","Pipeline و Analytics"],["tasks","وظایف"],["visits","بازدید ملک"],["crm","CRM مشتری + ملک"],["security","امنیت و دستگاه"]] as const).map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</nav>
    {error?<div className="ops-error">{error}</div>:null}
    {loading&&!data?<div className="ops-panel">در حال دریافت اطلاعات…</div>:null}

    {data&&tab==="overview"?<>
      <section className="ops-kpis">
        <article><CalendarCheck2/><span>وظایف امروز</span><strong>{todayTotals.tasks.toLocaleString("fa-IR")}</strong><small>{todayTotals.tasksDone.toLocaleString("fa-IR")} انجام‌شده</small></article>
        <article><MapPin/><span>بازدید امروز</span><strong>{todayTotals.visits.toLocaleString("fa-IR")}</strong><small>{todayTotals.visitsDone.toLocaleString("fa-IR")} تکمیل‌شده</small></article>
        <article><Phone/><span>تماس امروز</span><strong>{todayTotals.calls.toLocaleString("fa-IR")}</strong></article>
        <article><Users/><span>پیگیری سررسیدشده</span><strong>{todayTotals.followups.toLocaleString("fa-IR")}</strong></article>
        <article><Camera/><span>تصاویر امروز</span><strong>{todayTotals.captures.toLocaleString("fa-IR")}</strong></article>
        <article><Zap/><span>پیگیری خودکار</span><strong>{data.automation.created.toLocaleString("fa-IR")}</strong><small>{data.automation.overdue.toLocaleString("fa-IR")} مورد عقب‌افتاده</small></article>
      </section>
      <section className="ops-toolbar"><button className="ops-button primary" disabled={busy} onClick={()=>void run("generate_followups")}><Zap size={15}/> اجرای اتوماسیون پیگیری</button><button className="ops-button" disabled={busy} onClick={()=>void run("generate_daily_reports")}><BarChart3 size={15}/> تولید گزارش امروز</button><span>این عملیات فقط روی داده‌های کاری CRM/وظایف انجام می‌شود.</span></section>
      <section className="ops-grid"><article className="ops-panel"><div className="ops-panel-head"><h2>عملکرد ۳۰ روزه کارکنان</h2><span>امتیاز ترکیبی فعالیت</span></div><div className="ops-performance-table">{data.performance.map(p=><div className="ops-performance-row" key={p.staffId}><div><strong>{p.staffName}</strong><small>{p.role}</small></div><b>{p.score.toLocaleString("fa-IR")} امتیاز</b><span>وظیفه {p.tasksDone}</span><span>بازدید {p.visitsDone}</span><span>تماس {p.callsDone}</span><span>تعامل {p.interactions}</span><em>{p.overdueFollowUps} پیگیری عقب‌افتاده</em></div>)}</div></article>
        <article className="ops-panel"><div className="ops-panel-head"><h2>صف پیگیری امروز</h2><button onClick={()=>setTab("crm")}>مشاهده CRM</button></div>{data.contacts.filter(c=>c.nextFollowUpAt&&new Date(c.nextFollowUpAt).getTime()<=Date.now()).slice(0,10).map(c=><div className="ops-row" key={c.id}><div><strong>{c.name}</strong><small>{c.staffName} · {c.phone||"بدون تلفن"} · {statusLabel(c.leadStatus||"customer")}</small><small>{c.linkedProperties.map(p=>p.title).join("، ")||"بدون ملک مرتبط"}</small></div>{c.phone?<a className="ops-call" href={"tel:"+encodeURIComponent(c.phone)}><Phone size={14}/> تماس</a>:null}</div>)}{!data.contacts.some(c=>c.nextFollowUpAt&&new Date(c.nextFollowUpAt).getTime()<=Date.now())?<p className="ops-empty">پیگیری عقب‌افتاده‌ای در صف نیست.</p>:null}</article></section>
    </>:null}

    {data&&tab==="pipeline"?<section className="ops-grid">
      <article className="ops-panel"><div className="ops-panel-head"><h2>قیف فروش لیدها</h2><button className="ops-button" disabled={busy} onClick={()=>void run("refresh_lead_scores")}><Zap size={14}/> بروزرسانی امتیازها</button></div><div className="ops-pipeline">{data.pipeline.map(item=><div className="ops-pipeline-col" key={item.status}><strong>{statusLabel(item.status)}</strong><b>{item.count.toLocaleString("fa-IR")}</b>{data.leads.filter(l=>l.status===item.status).sort((a,b)=>0).slice(0,5).map(l=><div className="ops-pipeline-lead" key={l.id}><button type="button" onClick={()=>{setTab("crm");setLinkContactId(data.contacts.find(c=>c.leadId===l.id)?.id||"")}}><span>{l.name}</span><small>{l.neighborhood||"بدون محله"} · امتیاز {l.leadScore.toLocaleString("fa-IR")}/۱۰۰ · {l.matchCount.toLocaleString("fa-IR")} فایل پیشنهادی</small></button><select value={l.status} disabled={busy} onChange={e=>void leadStatus(l.id,e.target.value)} aria-label={"مرحله "+l.name}><option value="new">جدید</option><option value="contacted">تماس</option><option value="follow_up">پیگیری</option><option value="visited">بازدید</option><option value="contract">قرارداد</option><option value="closed">بسته‌شده</option></select></div>)}</div>)}</div></article>
      <article className="ops-panel"><h2>Analytics تبدیل</h2><div className="ops-analytics-grid"><div><span>کل لید فعال</span><b>{data.analytics.total.toLocaleString("fa-IR")}</b></div><div><span>رسیده به تماس</span><b>{data.analytics.contactRate.toLocaleString("fa-IR")}٪</b></div><div><span>رسیده به بازدید</span><b>{data.analytics.visitRate.toLocaleString("fa-IR")}٪</b></div><div><span>رسیده به قرارداد</span><b>{data.analytics.contractRate.toLocaleString("fa-IR")}٪</b></div><div><span>بسته‌شده</span><b>{data.analytics.closeRate.toLocaleString("fa-IR")}٪</b></div><div><span>میانگین زمان تماس</span><b>{data.analytics.avgHoursToContact.toLocaleString("fa-IR")} ساعت</b></div><div><span>میانگین امتیاز لید فعال</span><b>{Math.round(data.analytics.avgActiveScore).toLocaleString("fa-IR")}/۱۰۰</b></div><div><span>مشتری در قرارداد/نهایی</span><b>{(data.analytics.reachedContract).toLocaleString("fa-IR")}</b></div></div><p className="ops-hint">امتیاز لید بر اساس وضعیت Pipeline، تازگی تماس، پیگیری، فعالیت، بازدید، تطبیق فایل و سیگنال پیشنهاد قیمت محاسبه می‌شود.</p></article>
    </section>:null}

    {data&&tab==="tasks"?<section className="ops-grid"><article className="ops-panel"><h2>ساخت وظیفه</h2><div className="ops-form"><select value={staffId} onChange={e=>setStaffId(e.target.value)}>{staffOptions.map(s=><option value={s.id} key={s.id}>{s.name} · {s.role}</option>)}</select><input value={task.title} placeholder="عنوان وظیفه" onChange={e=>setTask(v=>({...v,title:e.target.value}))}/><textarea value={task.description} placeholder="شرح" onChange={e=>setTask(v=>({...v,description:e.target.value}))}/><select value={task.priority} onChange={e=>setTask(v=>({...v,priority:e.target.value}))}><option value="low">کم</option><option value="normal">عادی</option><option value="high">مهم</option><option value="urgent">فوری</option></select><input type="datetime-local" value={task.dueAt} onChange={e=>setTask(v=>({...v,dueAt:e.target.value}))}/><select value={task.customerId} onChange={e=>setTask(v=>({...v,customerId:e.target.value}))}><option value="">بدون مشتری</option>{data.contacts.map(c=><option value={c.id} key={c.id}>{c.name} · {c.phone}</option>)}</select><select value={task.propertyId} onChange={e=>setTask(v=>({...v,propertyId:e.target.value}))}><option value="">بدون ملک</option>{data.properties.map(p=><option value={p.id} key={p.id}>{p.title} · {p.neighborhood}</option>)}</select><button className="ops-button primary" disabled={busy} onClick={()=>void createTask()}><Plus size={15}/> ساخت وظیفه</button></div></article>
      <article className="ops-panel"><h2>وظایف فعال و خودکار</h2>{activeTasks.map(t=><div className="ops-row" key={t.id}><div><strong>{t.title} {t.automation?<span className="ops-badge">خودکار</span>:null}</strong><small>{t.staffName} · {t.priority} · موعد {faDate(t.dueAt)}</small><small>{t.customerId?"مشتری متصل است":"بدون مشتری"} {t.propertyId?" · ملک متصل است":""}</small></div><button onClick={()=>void taskStatus(t.id,"done")}>انجام شد</button></div>)}{!activeTasks.length?<p className="ops-empty">وظیفه فعالی وجود ندارد.</p>:null}</article></section>:null}

    {data&&tab==="visits"?<section className="ops-grid"><article className="ops-panel"><h2>ثبت بازدید ملک</h2><div className="ops-form"><select value={staffId} onChange={e=>setStaffId(e.target.value)}>{staffOptions.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select><input value={visit.title} placeholder="عنوان بازدید" onChange={e=>setVisit(v=>({...v,title:e.target.value}))}/><select value={visit.propertyId} onChange={e=>setVisit(v=>({...v,propertyId:e.target.value}))}><option value="">ملک را انتخاب کنید</option>{data.properties.map(p=><option value={p.id} key={p.id}>{p.title} · {p.neighborhood}</option>)}</select><input value={visit.address} placeholder="آدرس" onChange={e=>setVisit(v=>({...v,address:e.target.value}))}/><div className="ops-two"><input value={visit.targetLat} placeholder="Latitude" inputMode="decimal" onChange={e=>setVisit(v=>({...v,targetLat:e.target.value}))}/><input value={visit.targetLng} placeholder="Longitude" inputMode="decimal" onChange={e=>setVisit(v=>({...v,targetLng:e.target.value}))}/></div><div className="ops-two"><input value={visit.radiusM} placeholder="شعاع متر" inputMode="numeric" onChange={e=>setVisit(v=>({...v,radiusM:e.target.value}))}/><input value={visit.scheduledAt} type="datetime-local" onChange={e=>setVisit(v=>({...v,scheduledAt:e.target.value}))}/></div><textarea value={visit.notes} placeholder="یادداشت" onChange={e=>setVisit(v=>({...v,notes:e.target.value}))}/><button className="ops-button primary" disabled={busy} onClick={()=>void createVisit()}><MapPin size={15}/> ثبت بازدید</button></div></article>
      <article className="ops-panel"><h2>بازدیدهای پیش‌رو</h2>{openVisits.map(v=><div className="ops-row" key={v.id}><div><strong>{v.title}</strong><small>{v.staffName} · {faDate(v.scheduledAt)}</small><small>{v.address||"بدون آدرس"} · {v.propertyId?"ملک متصل":"بدون ملک"}</small></div><span className="ops-pill">{v.status}</span></div>)}{!openVisits.length?<p className="ops-empty">بازدیدی ثبت نشده.</p>:null}</article></section>:null}

    {data&&tab==="crm"?<section className="ops-crm-layout">
      <article className="ops-panel"><h2>CRM یکپارچه مشتری + ملک</h2><p className="ops-hint">یک مشتری می‌تواند به یک لید، چند ملک و چندین تعامل/پیگیری متصل باشد.</p><div className="ops-form"><select value={staffId} onChange={e=>setStaffId(e.target.value)}>{staffOptions.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select><input value={contact.name} placeholder="نام مشتری/مالک" onChange={e=>setContact(v=>({...v,name:e.target.value}))}/><input value={contact.phone} placeholder="شماره تماس" inputMode="tel" onChange={e=>setContact(v=>({...v,phone:e.target.value}))}/><select value={contact.type} onChange={e=>setContact(v=>({...v,type:e.target.value}))}><option value="customer">مشتری</option><option value="owner">مالک</option><option value="buyer">خریدار</option><option value="tenant">مستأجر</option><option value="builder">سازنده</option><option value="partner">همکار</option></select><select value={contact.leadId} onChange={e=>setContact(v=>({...v,leadId:e.target.value}))}><option value="">بدون لید</option>{data.leads.map(l=><option value={l.id} key={l.id}>{l.name} · {l.phone} · {statusLabel(l.status)}</option>)}</select><select multiple value={contactProperties} onChange={e=>setContactProperties(Array.from(e.target.selectedOptions).map(o=>o.value))}><option value="" disabled>ملک‌های مرتبط را با Ctrl انتخاب کنید</option>{data.properties.map(p=><option value={p.id} key={p.id}>{p.title} · {p.neighborhood}</option>)}</select><select value={contact.relationType} onChange={e=>setContact(v=>({...v,relationType:e.target.value}))}><option value="interested">علاقه‌مند</option><option value="viewing">در حال بازدید</option><option value="owner">مالک</option><option value="buyer">خریدار</option><option value="tenant">مستأجر</option><option value="seller">فروشنده</option><option value="related">مرتبط</option></select><input type="datetime-local" value={contact.nextFollowUpAt} onChange={e=>setContact(v=>({...v,nextFollowUpAt:e.target.value}))}/><textarea value={contact.notes} placeholder="یادداشت CRM" onChange={e=>setContact(v=>({...v,notes:e.target.value}))}/><button className="ops-button primary" disabled={busy} onClick={()=>void createContact()}><UserRound size={15}/> ثبت پرونده CRM</button></div>
      <hr className="ops-separator"/><h3>اتصال پرونده موجود</h3><div className="ops-form"><select value={linkContactId} onChange={e=>setLinkContactId(e.target.value)}><option value="">مخاطب را انتخاب کنید</option>{data.contacts.map(c=><option value={c.id} key={c.id}>{c.name} · {c.phone}</option>)}</select><select value={linkLeadId} onChange={e=>setLinkLeadId(e.target.value)}><option value="">بدون تغییر لید</option>{data.leads.map(l=><option value={l.id} key={l.id}>{l.name} · {l.phone}</option>)}</select><select multiple value={linkPropertyIds} onChange={e=>setLinkPropertyIds(Array.from(e.target.selectedOptions).map(o=>o.value))}>{data.properties.map(p=><option value={p.id} key={p.id}>{p.title} · {p.neighborhood}</option>)}</select><button className="ops-button" disabled={busy||!linkContactId} onClick={()=>void linkContact()}><Link2 size={15}/> اتصال لید و ملک‌ها</button></div></article>
      <article className="ops-panel"><h2>پرونده‌های CRM</h2>{data.contacts.map(c=><div className="ops-crm-card" key={c.id}><div className="ops-crm-card-head"><div><strong>{c.name}</strong><small>{c.staffName} · {c.phone||"بدون تلفن"} · {c.type}</small></div>{c.nextFollowUpAt?<span className={new Date(c.nextFollowUpAt).getTime()<=Date.now()?"ops-pill danger":"ops-pill"}>{new Date(c.nextFollowUpAt).getTime()<=Date.now()?"عقب‌افتاده":"پیگیری"} · {faDate(c.nextFollowUpAt)}</span>:null}</div><div className="ops-crm-tags">{c.leadId?<span>لید: {c.leadDeal||statusLabel(c.leadStatus||"")} · امتیاز {c.leadScore.toLocaleString("fa-IR")}/۱۰۰</span>:<span>بدون لید</span>}{c.linkedProperties.slice(0,5).map(p=><span key={p.id}>ملک: {p.title}</span>)}{c.recommendedProperties.slice(0,3).map((p:any)=><span key={"rec-"+String(p.id)}>پیشنهاد: {String(p.title||"ملک")} · {Number(p.score||0).toLocaleString("fa-IR")}%</span>)}</div><p>{c.notes||"یادداشت ثبت نشده است."}</p><div className="ops-crm-history">{(interactionMap.get(c.id)??[]).slice(0,4).map(i=><div key={i.id}><b>{i.kind}</b><span>{i.note||"—"}</span><small>{faDate(i.createdAt)}</small></div>)}</div>{c.phone?<a className="ops-call" href={"tel:"+encodeURIComponent(c.phone)}><Phone size={14}/> تماس با مشتری</a>:null}</div>)}{!data.contacts.length?<p className="ops-empty">هنوز پرونده CRM ساخته نشده است.</p>:null}</article>
    </section>:null}

    {data&&tab==="security"?<section className="ops-grid"><article className="ops-panel"><h2>امنیت و سلامت دستگاه</h2>{data.devices.map(d=><div className="ops-device" key={d.deviceId}><div><strong>{d.staffName}</strong><small>{d.manufacturer} {d.model} · Android {d.androidVersion||"—"} · {d.managementMode}</small><small>آخرین اتصال: {faDate(d.lastSeenAt)}</small>{d.lostMode?<b className="danger-text">⚠ {d.lostMessage||"دستگاه مفقود علامت‌گذاری شده است."}</b>:null}{(()=>{const h=data.health.find(x=>x.deviceId===d.deviceId);const p=h?.payload||{};return <small className="ops-health-line">سلامت: {p.battery?.batteryPercent==null?"—":p.battery.batteryPercent+"٪ باتری"} · {p.storageAvailableBytes==null?"—":Math.round(Number(p.storageAvailableBytes)/1048576).toLocaleString("fa-IR")+"MB آزاد"} · {p.network?.connected===true?"آنلاین":"آفلاین"}</small>})()}</div><button className={d.lostMode?"danger-btn":""} disabled={busy} onClick={()=>void deviceLost(d)}>{d.lostMode?"لغو حالت مفقودی":"علامت‌گذاری مفقود"}</button></div>)}</article>
      <article className="ops-panel"><h2>آخرین تصاویر املاک</h2><div className="ops-captures">{data.captures.slice(0,18).map(c=><a className="ops-capture" href={c.streamUrl} target="_blank" rel="noreferrer" key={c.id}><img src={c.streamUrl} alt={c.category}/><span>{c.staffName} · {c.category}</span><small>{faDate(c.createdAt)}</small></a>)}</div></article></section>:null}
  </div></main>;
}