import { useEffect,useState } from "react";
import { CheckCircle2,Clock3,Plus,RefreshCw,WalletCards } from "lucide-react";
import { toast } from "sonner";
const fa=(n:number)=>Number(n||0).toLocaleString("fa-IR");
const money=(n:number)=>fa(n)+" تومان";
type Status="pending"|"approved"|"paid"|"cancelled";
type Row={id:string;consultant:string;dealId:string|null;dealTitle:string|null;commissionAmount:number;consultantShare:number;officeShare:number;status:Status;paidAt:string|null;note:string};
export function AdminCommissionSettlement(){
 const [rows,setRows]=useState<Row[]>([]),[deals,setDeals]=useState<Array<{id:string;title:string;consultant:string;commission:number}>>([]),[sum,setSum]=useState<any>({}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 const [form,setForm]=useState({consultant:"",dealId:"",commission:"",consultantShare:"",note:""});
 const load=async()=>{setLoading(true);try{const r=await fetch("/api/admin-commission",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"list"})});const x=await r.json();if(!r.ok)throw new Error(x?.statusMessage||"بارگذاری تسویه انجام نشد.");setRows(x.settlements||[]);setDeals(x.deals||[]);setSum(x.summary||{});}catch(e){toast.error(e instanceof Error?e.message:"بارگذاری تسویه انجام نشد.");}finally{setLoading(false);}};
 useEffect(()=>{void load()},[]);
 const create=async()=>{setSaving(true);try{const r=await fetch("/api/admin-commission",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"create",...form})});const x=await r.json();if(!r.ok)throw new Error(x?.statusMessage||"ثبت تسویه انجام نشد.");toast.success("تسویه در صف پرداخت ثبت شد.");setForm(v=>({...v,consultant:"",dealId:"",commission:"",consultantShare:"",note:""}));await load();}catch(e){toast.error(e instanceof Error?e.message:"ثبت تسویه انجام نشد.");}finally{setSaving(false);}};
 const status=async(id:string,value:Status)=>{const r=await fetch("/api/admin-commission",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"status",id,status:value})});if(r.ok){setRows(v=>v.map(x=>x.id===id?{...x,status:value,paidAt:value==="paid"?new Date().toISOString():x.paidAt}:x));toast.success("وضعیت تسویه به‌روزرسانی شد.");}};
 return <div className="admin-commission"><div className="admin-dashboard-mini-grid"><div><span>در انتظار</span><strong>{fa(sum.pending)}</strong></div><div><span>تأییدشده</span><strong>{fa(sum.approved)}</strong></div><div><span>پرداخت‌شده</span><strong>{fa(sum.paid)}</strong></div><div><span>سهم قابل پرداخت</span><strong>{money(sum.total)}</strong></div></div>
 <div className="admin-commission-grid"><section className="admin-panel"><div className="admin-panel-head"><div><span className="kicker">تسویه</span><h2>تسویه کمیسیون مشاوران</h2></div><button className="btn-ghost" type="button" onClick={()=>void load()} disabled={loading}><RefreshCw size={14}/> بروزرسانی</button></div>
 <div className="admin-form-grid"><label className="field"><span>مشاور</span><input value={form.consultant} onChange={e=>setForm(v=>({...v,consultant:e.target.value}))}/></label><label className="field"><span>معامله مرتبط</span><select value={form.dealId} onChange={e=>{const d=deals.find(x=>x.id===e.target.value);setForm(v=>({...v,dealId:e.target.value,consultant:d?.consultant||v.consultant,commission:d?.commission?String(d.commission):v.commission}))}}><option value="">بدون اتصال</option>{deals.map(d=><option key={d.id} value={d.id}>{d.title+" · "+d.consultant+" · "+money(d.commission||0)}</option>)}</select></label><label className="field"><span>کمیسیون کل</span><input inputMode="numeric" value={form.commission} onChange={e=>setForm(v=>({...v,commission:e.target.value}))}/></label><label className="field"><span>سهم مشاور</span><input inputMode="numeric" value={form.consultantShare} onChange={e=>setForm(v=>({...v,consultantShare:e.target.value}))}/></label><label className="field admin-span-2"><span>یادداشت</span><textarea value={form.note} onChange={e=>setForm(v=>({...v,note:e.target.value}))}/></label></div><button className="btn-gold" type="button" onClick={()=>void create()} disabled={saving}><Plus size={15}/>{saving?"در حال ثبت…":"ثبت تسویه"}</button></section>
 <section className="admin-panel"><div className="admin-panel-head"><div><span className="kicker">صف پرداخت</span><h2>تسویه‌های اخیر</h2></div></div><div className="admin-commission-list">{rows.map(r=><article className="admin-commission-row" key={r.id}><div><strong>{r.consultant}</strong><small>{r.dealTitle||"بدون معامله"} · کمیسیون {money(r.commissionAmount)} · سهم مشاور {money(r.consultantShare)}</small></div><div><b>سهم دفتر {money(r.officeShare)}</b><small>{r.note||"—"}</small></div><select value={r.status} onChange={e=>void status(r.id,e.target.value as Status)}><option value="pending">در انتظار</option><option value="approved">تأیید شده</option><option value="paid">پرداخت شد</option><option value="cancelled">لغو شد</option></select></article>)}{!rows.length&&!loading?<div className="admin-empty"><WalletCards size={25}/><strong>هنوز تسویه‌ای ثبت نشده.</strong></div>:null}</div></section></div></div>;
}
