import { useCallback, useEffect, useState } from "react";
import { AlertTriangle, CheckCircle2, ExternalLink, RefreshCw, ShieldAlert, Wrench } from "lucide-react";
import { toast } from "sonner";
import { adminErrorMessage } from "@/components/hirmand/admin-ui-utils";
type Issue={id:string;slug:string;title:string;neighborhood:string;severity:"high"|"medium";code:string;label:string;detail:string;status:string;updatedAt:string};
type Duplicate={kind:string;label:string;key:string;context:string;fileCount:number;files:Array<{id:string;slug:string;title:string;neighborhood:string}>};
type Data={generatedAt:string;stats:{issues:number;high:number;duplicateGroups:number};issues:Issue[];duplicates:Duplicate[]};
const CSS=[".pic{display:grid;gap:14px;margin:18px 0}",".pic-head{display:flex;justify-content:space-between;align-items:center;gap:10px;flex-wrap:wrap}",".pic-head h2{margin:0;color:var(--navy-900);font-size:1rem}.pic-head p{margin:4px 0 0;color:var(--muted);font-size:.68rem}",".pic-stats{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}",".pic-stat{padding:12px 14px;background:var(--card);border:1px solid var(--line);border-radius:var(--r-lg)}",".pic-stat small{display:block;color:var(--muted);font-size:.66rem}.pic-stat strong{display:block;margin-top:5px;color:var(--navy-900);font-size:1.15rem}",".pic-grid{display:grid;grid-template-columns:minmax(0,1.1fr) minmax(280px,.9fr);gap:12px}",".pic-list{display:grid;gap:7px}",".pic-issue{display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:9px;align-items:start;padding:10px 11px;border:1px solid var(--line);border-radius:10px;background:var(--card)}",".pic-issue[data-severity='high']{border-color:rgb(163 49 39 / 26%);background:var(--danger-bg)}.pic-issue strong{color:var(--navy-900);font-size:.73rem}.pic-issue small{display:block;margin-top:2px;color:var(--muted);font-size:.63rem;line-height:1.7}",".pic-dup{display:grid;gap:6px;padding:10px 11px;border:1px solid var(--line);border-radius:10px;background:var(--card)}.pic-dup strong{font-size:.72rem;color:var(--navy-900)}.pic-links{display:flex;gap:5px;flex-wrap:wrap}.pic-links a{display:inline-flex;gap:4px;align-items:center;padding:5px 7px;border:1px solid var(--line);border-radius:8px;background:var(--card-2);font-size:.63rem;color:var(--navy-900);text-decoration:none}",".pic-empty{padding:18px;text-align:center;border:1px dashed var(--line-2);border-radius:10px;color:var(--subtle);font-size:.68rem}","@media(max-width:900px){.pic-grid{grid-template-columns:1fr}}","@media(max-width:620px){.pic-stats{grid-template-columns:1fr}.pic-issue{grid-template-columns:minmax(0,1fr)}.pic-issue button{justify-self:start}}"].join("\\n");
export function AdminPropertyIntegrityCenter(){
  const [data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState("");
  const load=useCallback(async()=>{setLoading(true);try{const res=await fetch("/api/admin-property-integrity",{method:"POST",headers:{"content-type":"application/json"},credentials:"same-origin",body:JSON.stringify({action:"summary"})});const body=await res.json().catch(()=>({})) as Data&{statusMessage?:string};if(!res.ok)throw new Error(body.statusMessage||"مرکز سلامت فایل‌ها بارگذاری نشد.");setData(body);}catch(e){toast.error(adminErrorMessage(e,"مرکز سلامت فایل‌ها بارگذاری نشد."));}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  async function createTask(issue:Issue){if(busy)return;setBusy(issue.id+issue.code);try{const res=await fetch("/api/admin-property-integrity",{method:"POST",headers:{"content-type":"application/json"},credentials:"same-origin",body:JSON.stringify({action:"create_task",propertyId:issue.id,title:"بررسی فایل: "+issue.label+" · "+issue.title,issue:issue.severity,detail:issue.detail})});const body=await res.json().catch(()=>({})) as {statusMessage?:string};if(!res.ok)throw new Error(body.statusMessage||"وظیفه ساخته نشد.");toast.success(body.statusMessage||(body as {alreadyExists?:boolean}).alreadyExists?"وظیفه از قبل وجود دارد.":"وظیفه بررسی ساخته شد.");}catch(e){toast.error(adminErrorMessage(e,"وظیفه ساخته نشد."));}finally{setBusy("");}}
  return <section className="admin-panel pic"><style>{CSS}</style><div className="pic-head"><div><span className="kicker">Property Data Integrity</span><h2>مرکز کنترل تکراری و ناسازگاری فایل‌ها</h2><p>اشکالات ساختاری و سیگنال‌های تکراری را پیش از انتشار در گزارش‌ها و CRM پیدا کنید.</p></div><button className="btn-ghost" type="button" onClick={()=>void load()} disabled={loading}><RefreshCw size={15} className={loading?"admin-spin":undefined}/>بررسی دوباره</button></div>
    <div className="pic-stats"><div className="pic-stat"><small>موارد نیازمند بررسی</small><strong>{(data?.stats.issues??0).toLocaleString("fa-IR")}</strong></div><div className="pic-stat"><small>هشدارهای مهم</small><strong>{(data?.stats.high??0).toLocaleString("fa-IR")}</strong></div><div className="pic-stat"><small>گروه تکراری احتمالی</small><strong>{(data?.stats.duplicateGroups??0).toLocaleString("fa-IR")}</strong></div></div>
    <div className="pic-grid"><section><div className="admin-panel-head"><div><span className="kicker">Data Quality</span><h3>ناسازگاری‌ها</h3></div><ShieldAlert size={17} color="var(--brass-700)"/></div>{data?.issues.length?<div className="pic-list">{data.issues.slice(0,24).map(issue=><article className="pic-issue" data-severity={issue.severity} key={issue.id+"-"+issue.code}>{issue.severity==="high"?<AlertTriangle size={16}/>:<Wrench size={15}/>}<div><strong>{issue.label} · {issue.title}</strong><small>{issue.neighborhood||"بدون محله"} · {issue.detail}</small></div><div style={{display:"flex",gap:5,flexWrap:"wrap"}}><button className="btn-ghost" type="button" onClick={()=>void createTask(issue)} disabled={Boolean(busy)}><CheckCircle2 size={13}/>ساخت وظیفه</button><a className="btn-ghost" href={"/properties/"+encodeURIComponent(issue.slug)} target="_blank" rel="noreferrer"><ExternalLink size={13}/>فایل</a></div></article>)}</div>:<div className="pic-empty">{loading?"در حال بررسی…":"مورد ناسازگاری پیدا نشد."}</div>}</section>
      <section><div className="admin-panel-head"><div><span className="kicker">Duplicate Signals</span><h3>تکراری‌های احتمالی</h3></div><AlertTriangle size={17} color="var(--brass-700)"/></div>{data?.duplicates.length?<div className="pic-list">{data.duplicates.slice(0,12).map(group=><div className="pic-dup" key={group.kind+group.key}><strong>{group.label} · {group.fileCount.toLocaleString("fa-IR")} فایل</strong><small style={{color:"var(--muted)"}}>{group.context}</small><div className="pic-links">{group.files.map(file=><a key={file.id} href={"/properties/"+encodeURIComponent(file.slug)} target="_blank" rel="noreferrer">{file.title||file.id.slice(0,7)} <ExternalLink size={10}/></a>)}</div></div>)}</div>:<div className="pic-empty">سیگنال تکراری پیدا نشد.</div>}</section>
    </div>
  </section>;
}
