import { useCallback,useEffect,useState } from "react";
import { AlertTriangle, CircleCheck, Link2Off, RefreshCw, WalletCards } from "lucide-react";
import { toast } from "sonner";
type Data={days:number;summary:{income:number;expense:number;balance:number;linked:number;unlinked:number;duplicates:number};rows:Array<{id:number;kind:string;title:string;amount:number;transactionDate:string;propertyId:string|null;leadId:string|null;consultant:string;category:string;propertyTitle:string|null;leadName:string|null}>;consultants:Array<{consultant:string;income:number;expense:number;count:number;linked:number}>};
const fa=(n:number)=>Math.round(n).toLocaleString("fa-IR");const money=(n:number)=>fa(n)+" تومان";const date=(v:string)=>{try{return new Intl.DateTimeFormat("fa-IR").format(new Date(v+"T12:00:00"));}catch{return v;}};
export function AdminFinanceReconciliation(){
 const [days,setDays]=useState(90),[data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);try{const res=await fetch("/api/admin-finance-reconciliation",{method:"POST",headers:{"content-type":"application/json"},credentials:"same-origin",body:JSON.stringify({days})});const d=await res.json().catch(()=>({}));if(!res.ok)throw new Error(d?.statusMessage||"گزارش تطبیق دفتر مالی دریافت نشد.");setData(d as Data);}catch(e){toast.error(e instanceof Error?e.message:"گزارش مالی دریافت نشد.");}finally{setLoading(false);}},[days]);
 useEffect(()=>{void load();},[load]);
 return <main className="admin-finance-reconciliation">
  <section className="admin-panel"><div className="admin-panel-head"><div><span className="kicker">کنترل حساب</span><h2>تطبیق دفتر مالی</h2><p className="admin-finance-recon-lede">تراکنش‌های بدون اتصال به فایل یا لید و موارد تکراری مشکوک را جدا می‌کند تا دفتر مالی تمیزتر بماند.</p></div><div className="admin-finance-recon-toolbar">{[30,90,365].map(v=><button type="button" key={v} className={days===v?"is-active":""} onClick={()=>setDays(v)}>{v===30?"۳۰ روز":v===90?"۹۰ روز":"یک سال"}</button>)}<button type="button" className="btn-ghost" onClick={()=>void load()} disabled={loading}><RefreshCw size={15} className={loading?"admin-spin":""}/>بروزرسانی</button></div></div>
   <div className="admin-finance-recon-grid"><div><span>درآمد</span><strong>{money(data?.summary.income??0)}</strong></div><div><span>هزینه</span><strong>{money(data?.summary.expense??0)}</strong></div><div><span>تراکنش متصل</span><strong>{fa(data?.summary.linked??0)}</strong></div><div className={(data?.summary.unlinked??0)>0?"is-warn":""}><span>بدون اتصال</span><strong>{fa(data?.summary.unlinked??0)}</strong></div><div className={(data?.summary.duplicates??0)>0?"is-warn":""}><span>تکراری مشکوک</span><strong>{fa(data?.summary.duplicates??0)}</strong></div></div>
  </section>
  <section className="admin-panel"><div className="admin-panel-head"><div><span className="kicker">موارد نیازمند بررسی</span><h2>{fa(data?.rows.length??0)} رکورد علامت‌گذاری‌شده</h2></div></div>
   {loading&&!data?<div className="admin-empty"><RefreshCw size={22} className="admin-spin"/><strong>در حال بررسی تراکنش‌ها…</strong></div>:!data?.rows.length?<div className="admin-empty"><CircleCheck size={26}/><strong>مورد مشکوکی پیدا نشد.</strong><p>تراکنش‌های این بازه مورد بدون اتصال یا الگوی تکراری ندارند.</p></div>:
   <div className="admin-finance-recon-list">{data.rows.map(row=><article className="admin-finance-recon-row" key={row.id}><span className={"admin-finance-recon-icon "+(row.propertyId||row.leadId?"linked":"unlinked")}>{row.propertyId||row.leadId?<WalletCards size={17}/>:<Link2Off size={17}/>}</span><div><strong>{row.title}</strong><p>{money(row.amount)} · {date(row.transactionDate)}{row.consultant?" · "+row.consultant:""}</p><small>{row.propertyTitle?"فایل: "+row.propertyTitle:row.leadName?"لید: "+row.leadName:"بدون ارتباط با فایل یا لید"}{row.category?" · "+row.category:""}</small></div><span className={row.propertyId||row.leadId?"admin-finance-recon-tag":"admin-finance-recon-tag is-warn"}>{row.propertyId||row.leadId?"تکراری؟":"نیازمند اتصال"}</span></article>)}</div>}
  </section>
  <section className="admin-panel"><div className="admin-panel-head"><div><span className="kicker">تفکیک مشاور</span><h2>تراز ثبت‌شده به تفکیک مشاور</h2></div></div><div className="admin-finance-consultant-table"><div className="admin-finance-consultant-head"><span>مشاور</span><span>درآمد</span><span>هزینه</span><span>مانده</span><span>اتصال</span></div>{(data?.consultants??[]).map(r=><div className="admin-finance-consultant-row" key={r.consultant}><strong>{r.consultant}</strong><span>{money(r.income)}</span><span>{money(r.expense)}</span><span>{money(r.income-r.expense)}</span><span>{fa(r.linked)} / {fa(r.count)}</span></div>)}</div></section>
 </main>;
}
