import { useCallback,useEffect,useMemo,useState } from "react";
import { BriefcaseBusiness,CheckCircle2,CircleAlert,FileCheck2,Plus,RefreshCw,Trash2 } from "lucide-react";
import { toast } from "sonner";
type DealStatus="prospect"|"negotiation"|"agreement"|"contracted"|"completed"|"cancelled"; type DealType="sale"|"rent"|"mortgage"|"buy"; type DocStatus="pending"|"received"|"verified"|"rejected";
type Deal={id:string;leadId:string|null;propertyId:string|null;title:string;type:DealType;status:DealStatus;customerName:string;customerPhone:string;consultant:string;amount:number|null;commission:number|null;contractNumber:string;contractDate:string|null;closingDate:string|null;notes:string;propertyTitle:string|null};
type Doc={id:string;documentType:string;status:DocStatus;fileUrl:string;note:string;receivedAt:string|null;verifiedAt:string|null};
type Meta={id:string;name:string;phone:string;consultant:string;status:string}; type PropertyMeta={id:string;title:string;neighborhood:string};
const TYPES:Record<DealType,string>={sale:"فروش",rent:"اجاره",mortgage:"رهن",buy:"خرید"}; const STATUSES:Record<DealStatus,string>={prospect:"در حال پیگیری",negotiation:"مذاکره",agreement:"توافق",contracted:"قرارداد امضا شد",completed:"نهایی شد",cancelled:"لغو شد"}; const DOCS:Record<DocStatus,string>={pending:"در انتظار",received:"دریافت شد",verified:"تأیید شد",rejected:"رد شد"};
const fa=(n:number)=>Number(n||0).toLocaleString("fa-IR"); const money=(n:number|null)=>n==null?"—":fa(n)+" تومان";
export function AdminDealsManager(){
 const [deals,setDeals]=useState<Deal[]>([]),[leads,setLeads]=useState<Meta[]>([]),[properties,setProperties]=useState<PropertyMeta[]>([]),[stats,setStats]=useState<Record<string,number>>({}),[selected,setSelected]=useState<string|null>(null),[docs,setDocs]=useState<Doc[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 const [form,setForm]=useState({title:"",customerName:"",customerPhone:"",consultant:"",dealType:"sale" as DealType,status:"prospect" as DealStatus,amount:"",commission:"",contractNumber:"",contractDate:"",closingDate:"",leadId:"",propertyId:"",notes:""});
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch("/api/admin-deals",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"list"})});const x=await r.json();if(!r.ok)throw new Error(x?.statusMessage||"دریافت معاملات انجام نشد.");setDeals(x.deals||[]);setLeads(x.leads||[]);setProperties(x.properties||[]);setStats(x.stats||{});}catch(e){toast.error(e instanceof Error?e.message:"دریافت معاملات انجام نشد.");}finally{setLoading(false);}},[]);
 const loadDocs=useCallback(async(id:string)=>{const r=await fetch("/api/admin-deals",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"documents",id})});const x=await r.json();if(r.ok)setDocs(x.documents||[]);},[]);
 useEffect(()=>{void load();},[load]); useEffect(()=>{if(selected)void loadDocs(selected);else setDocs([]);},[selected,loadDocs]);
 const create=async()=>{if(!form.title.trim()||!form.customerName.trim())return toast.error("عنوان معامله و نام مشتری را وارد کنید.");setSaving(true);try{const r=await fetch("/api/admin-deals",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"create",...form})});const x=await r.json();if(!r.ok)throw new Error(x?.statusMessage||"ثبت معامله انجام نشد.");toast.success("معامله ثبت شد.");await load();setSelected(x.id);setForm(v=>({...v,title:"",customerName:"",customerPhone:"",amount:"",commission:"",notes:""}));}catch(e){toast.error(e instanceof Error?e.message:"ثبت معامله انجام نشد.");}finally{setSaving(false);}};
 const status=async(id:string,value:DealStatus)=>{const r=await fetch("/api/admin-deals",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"status",id,status:value})});if(r.ok)setDeals(v=>v.map(d=>d.id===id?{...d,status:value}:d));};
 const seed=async()=>{if(!selected)return;await fetch("/api/admin-deals",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"seed_documents",id:selected})});await loadDocs(selected);toast.success("چک‌لیست استاندارد ساخته شد.");};
 const docStatus=async(d:Doc,value:DocStatus)=>{if(!selected)return;const r=await fetch("/api/admin-deals",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"document",id:selected,documentType:d.documentType,documentStatus:value,fileUrl:d.fileUrl,note:d.note})});if(r.ok)await loadDocs(selected);};
 const remove=async(id:string)=>{if(!window.confirm("این معامله و مدارک آن حذف شود؟"))return;const r=await fetch("/api/admin-deals",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"delete",id})});if(r.ok){setSelected(null);await load();toast.success("معامله حذف شد.");}};
 const active=useMemo(()=>deals.find(d=>d.id===selected)||null,[deals,selected]);
 return <div className="admin-deals" dir="rtl">
  <div className="admin-deals-grid">
   <section className="admin-panel"><div className="admin-panel-head"><div><span className="kicker">معاملات</span><h2>دفتر قراردادها و معاملات</h2></div><button className="btn-ghost" type="button" onClick={()=>void load()} disabled={loading}><RefreshCw size={14}/> بروزرسانی</button></div>
    <div className="admin-dashboard-mini-grid"><div><span>کل</span><strong>{fa(stats.total)}</strong></div><div><span>مذاکره</span><strong>{fa(stats.negotiation)}</strong></div><div><span>قراردادی</span><strong>{fa(stats.contracted)}</strong></div><div><span>نهایی</span><strong>{fa(stats.completed)}</strong></div><div><span>حجم</span><strong>{money(stats.volume)}</strong></div><div><span>کمیسیون</span><strong>{money(stats.commissions)}</strong></div></div>
    <div className="admin-deal-list">{deals.map(d=><article className={"admin-deal-row "+(selected===d.id?"is-active":"")} key={d.id} onClick={()=>setSelected(d.id)}><div><strong>{d.title}</strong><span>{d.customerName+" · "+TYPES[d.type]+" · "+(d.propertyTitle||"بدون فایل")}</span></div><div><b>{money(d.amount)}</b><small>{d.commission!=null?"کمیسیون "+money(d.commission):"کمیسیون ثبت نشده"}</small></div><select value={d.status} onClick={e=>e.stopPropagation()} onChange={e=>void status(d.id,e.target.value as DealStatus)}>{Object.entries(STATUSES).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select>{selected===d.id?<button type="button" className="text-link" onClick={e=>{e.stopPropagation();void remove(d.id)}}><Trash2 size={13}/> حذف</button>:null}</article>)}{!deals.length&&!loading?<div className="admin-empty"><BriefcaseBusiness size={26}/><strong>هنوز معامله‌ای ثبت نشده.</strong></div>:null}</div>
   </section>
   <section className="admin-panel"><div className="admin-panel-head"><div><span className="kicker">ثبت</span><h2>معامله جدید</h2></div><Plus size={17}/></div>
    <div className="admin-form-grid">
     <label className="field"><span>عنوان معامله</span><input value={form.title} onChange={e=>setForm(v=>({...v,title:e.target.value}))}/></label>
     <label className="field"><span>نام مشتری</span><input value={form.customerName} onChange={e=>setForm(v=>({...v,customerName:e.target.value}))}/></label>
     <label className="field"><span>شماره تماس</span><input value={form.customerPhone} onChange={e=>setForm(v=>({...v,customerPhone:e.target.value}))}/></label>
     <label className="field"><span>مشاور</span><input value={form.consultant} onChange={e=>setForm(v=>({...v,consultant:e.target.value}))}/></label>
     <label className="field"><span>مبلغ معامله</span><input inputMode="numeric" value={form.amount} onChange={e=>setForm(v=>({...v,amount:e.target.value}))}/></label>
     <label className="field"><span>کمیسیون</span><input inputMode="numeric" value={form.commission} onChange={e=>setForm(v=>({...v,commission:e.target.value}))}/></label>
     <label className="field"><span>شماره قرارداد</span><input value={form.contractNumber} onChange={e=>setForm(v=>({...v,contractNumber:e.target.value}))}/></label>
     <label className="field"><span>نوع معامله</span><select value={form.dealType} onChange={e=>setForm(v=>({...v,dealType:e.target.value as DealType}))}>{Object.entries(TYPES).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
     <label className="field"><span>وضعیت</span><select value={form.status} onChange={e=>setForm(v=>({...v,status:e.target.value as DealStatus}))}>{Object.entries(STATUSES).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
     <label className="field"><span>اتصال به لید</span><select value={form.leadId} onChange={e=>{const id=e.target.value;const l=leads.find(x=>x.id===id);setForm(v=>({...v,leadId:id,customerName:l?.name||v.customerName,customerPhone:l?.phone||v.customerPhone,consultant:l?.consultant||v.consultant}))}}><option value="">بدون اتصال</option>{leads.map(l=><option key={l.id} value={l.id}>{l.name+" · "+l.phone}</option>)}</select></label>
     <label className="field"><span>فایل مرتبط</span><select value={form.propertyId} onChange={e=>setForm(v=>({...v,propertyId:e.target.value}))}><option value="">بدون فایل</option>{properties.map(p=><option key={p.id} value={p.id}>{p.title+" · "+p.neighborhood}</option>)}</select></label>
     <label className="field"><span>تاریخ قرارداد</span><input type="date" value={form.contractDate} onChange={e=>setForm(v=>({...v,contractDate:e.target.value}))}/></label>
     <label className="field"><span>تاریخ نهایی‌شدن</span><input type="date" value={form.closingDate} onChange={e=>setForm(v=>({...v,closingDate:e.target.value}))}/></label>
     <label className="field admin-span-2"><span>یادداشت</span><textarea value={form.notes} onChange={e=>setForm(v=>({...v,notes:e.target.value}))}/></label>
    </div><button className="btn-gold" type="button" onClick={()=>void create()} disabled={saving}><Plus size={15}/>{saving?"در حال ثبت…":"ثبت معامله"}</button>
   </section>
  </div>
  {active?<section className="admin-panel"><div className="admin-panel-head"><div><span className="kicker">مدارک</span><h2>چک‌لیست مدارک · {active.title}</h2><p>مدارک را از «در انتظار» تا «تأیید شد» کنترل کنید.</p></div><button className="btn-ghost" type="button" onClick={()=>void seed()}><FileCheck2 size={15}/> ساخت چک‌لیست استاندارد</button></div>
   <div className="admin-doc-list">{docs.map(d=><div className="admin-doc-row" key={d.documentType}><div><strong>{d.documentType}</strong><small>{d.note||"بدون یادداشت"}</small></div><select value={d.status} onChange={e=>void docStatus(d,e.target.value as DocStatus)}>{Object.entries(DOCS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><span className={"admin-doc-badge "+d.status}>{DOCS[d.status]}</span>{d.status==="verified"?<CheckCircle2 size={16}/>:d.status==="rejected"?<CircleAlert size={16}/>:<FileCheck2 size={16}/>}</div>)}{!docs.length?<div className="admin-empty">برای این معامله هنوز چک‌لیست ساخته نشده.</div>:null}</div>
  </section>:null}
 </div>;
}
