import { CalendarClock, Check, EyeOff, MessageCircleQuestion, RefreshCw, Send, Trash2, UsersRound } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { toast } from "sonner";
import "@/property-feature-enhancements.css";
import { PersianDateTimePicker } from "./persian-date-time-picker";

type Question={id:string;question:string;answer:string;status:"pending"|"answered"|"hidden";statusLabel:string;createdAt:string;answeredAt:string|null;};
type EventItem={id:string;startsAt:string;endsAt:string;capacity:number;bookedSeats:number;remainingSeats:number;note:string;status:"scheduled"|"cancelled";};
type Rsvp={id:string;eventId:string;name:string;phone:string;partySize:number;note:string;status:string;createdAt:string;};

export function AdminPropertyQuestions({propertyId}:{propertyId:string}){
 const[items,setItems]=useState<Question[]>([]);const[drafts,setDrafts]=useState<Record<string,string>>({});const[loading,setLoading]=useState(true);const[busyId,setBusyId]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);try{const response=await fetch("/api/property-questions",{method:"POST",headers:{"content-type":"application/json"},credentials:"same-origin",body:JSON.stringify({action:"admin_list",propertyId})});const data=await response.json().catch(()=>null) as {questions?:Question[];statusMessage?:string};if(!response.ok)throw new Error(data?.statusMessage||"پرسش‌های فایل بارگذاری نشد.");const next=Array.isArray(data?.questions)?data.questions:[];setItems(next);setDrafts(Object.fromEntries(next.map(item=>[item.id,item.answer||""])))}catch(error){toast.error(error instanceof Error?error.message:"پرسش‌های فایل بارگذاری نشد.");}finally{setLoading(false);}},[propertyId]);
 useEffect(()=>{void load();},[load]);
 async function act(action:"answer"|"hide",id:string){const answer=(drafts[id]||"").trim();if(action==="answer"&&answer.length<2){toast.error("پاسخ را وارد کنید.");return;}setBusyId(id);try{const body=action==="answer"?{action,id,answer}:{action,id};const response=await fetch("/api/property-questions",{method:"POST",headers:{"content-type":"application/json"},credentials:"same-origin",body:JSON.stringify(body)});const data=await response.json().catch(()=>null) as {statusMessage?:string};if(!response.ok)throw new Error(data?.statusMessage||"عملیات انجام نشد.");toast.success(action==="answer"?"پاسخ روی فایل منتشر شد.":"پرسش پنهان شد.");await load();}catch(error){toast.error(error instanceof Error?error.message:"عملیات انجام نشد.");}finally{setBusyId(null);}}
 return <section className="admin-section admin-property-questions" aria-label="پرسش و پاسخ عمومی فایل"><div className="admin-property-feature-head"><div><span className="kicker">تعامل عمومی</span><h3><MessageCircleQuestion size={18}/> پرسش‌وپاسخ فایل</h3><p>سؤال مشتری جمع می‌شود و فقط پاسخ‌های تأییدشده عمومی می‌شوند.</p></div><button type="button" className="btn-ghost" onClick={()=>void load()} disabled={loading}><RefreshCw size={15}/> بروزرسانی</button></div>{loading&&!items.length?<div className="admin-empty">در حال دریافت پرسش‌ها…</div>:!items.length?<div className="admin-empty">هنوز پرسشی برای این فایل ثبت نشده است.</div>:<div className="admin-property-feature-list">{items.map(item=><article className="admin-property-feature-row" key={item.id}><div className="admin-property-feature-row-main"><div className="admin-property-feature-row-meta"><span>{item.statusLabel}</span><small>{new Date(item.createdAt).toLocaleString("fa-IR",{timeZone:"Asia/Tehran"})}</small></div><strong>{item.question}</strong></div>{item.status==="pending"?<div className="admin-property-question-answer"><textarea rows={3} value={drafts[item.id]||""} onChange={e=>setDrafts(cur=>({...cur,[item.id]:e.target.value.slice(0,1200)}))} placeholder="پاسخ حرفه‌ای و کوتاه مشاور…"/><div className="admin-property-feature-actions"><button type="button" className="btn-gold" onClick={()=>void act("answer",item.id)} disabled={busyId===item.id}><Send size={14}/> پاسخ و انتشار</button><button type="button" className="btn-ghost" onClick={()=>void act("hide",item.id)} disabled={busyId===item.id}><EyeOff size={14}/> پنهان</button></div></div>:item.status==="answered"?<div className="admin-property-question-answer"><div className="admin-property-question-preview"><Check size={14}/>{item.answer}</div><button type="button" className="btn-ghost" onClick={()=>void act("hide",item.id)} disabled={busyId===item.id}><EyeOff size={14}/> پنهان</button></div>:null}</article>)}</div>}</section>;
}

function toIso(value:string){const d=new Date(value);return Number.isFinite(d.getTime())?d.toISOString():"";}
function faDate(value:string){try{return new Intl.DateTimeFormat("fa-IR-u-ca-persian",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Tehran"}).format(new Date(value));}catch{return value;}}
export function AdminPropertyOpenHouse({propertyId}:{propertyId:string}){
 const[items,setItems]=useState<EventItem[]>([]);const[rsvps,setRsvps]=useState<Rsvp[]>([]);const[startsAt,setStartsAt]=useState("");const[endsAt,setEndsAt]=useState("");const[capacity,setCapacity]=useState("8");const[note,setNote]=useState("");const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{setLoading(true);try{const response=await fetch("/api/property-open-house",{method:"POST",headers:{"content-type":"application/json"},credentials:"same-origin",body:JSON.stringify({action:"admin_list",propertyId})});const data=await response.json().catch(()=>null) as {events?:EventItem[];rsvps?:Rsvp[];statusMessage?:string};if(!response.ok)throw new Error(data?.statusMessage||"برنامه اوپن‌هاوس بارگذاری نشد.");setItems(Array.isArray(data?.events)?data.events:[]);setRsvps(Array.isArray(data?.rsvps)?data.rsvps:[]);}catch(error){toast.error(error instanceof Error?error.message:"برنامه اوپن‌هاوس بارگذاری نشد.");}finally{setLoading(false);}},[propertyId]);
 useEffect(()=>{void load();},[load]);
 async function createEvent(){const start=toIso(startsAt),end=toIso(endsAt),cap=Math.min(100,Math.max(1,Number(capacity)||8));if(!start||!end){toast.error("زمان شروع و پایان را کامل کنید.");return;}if(new Date(end).getTime()<=new Date(start).getTime()){toast.error("زمان پایان باید بعد از شروع باشد.");return;}setBusy(true);try{const response=await fetch("/api/property-open-house",{method:"POST",headers:{"content-type":"application/json"},credentials:"same-origin",body:JSON.stringify({action:"create",propertyId,startsAt:start,endsAt:end,capacity:cap,note:note.trim()})});const data=await response.json().catch(()=>null) as {statusMessage?:string};if(!response.ok)throw new Error(data?.statusMessage||"ساخت بازدید گروهی انجام نشد.");toast.success("زمان اوپن‌هاوس ثبت شد.");setStartsAt("");setEndsAt("");setNote("");await load();}catch(error){toast.error(error instanceof Error?error.message:"ساخت بازدید گروهی انجام نشد.");}finally{setBusy(false);}}
 async function cancel(id:string){if(!window.confirm("این زمان بازدید گروهی لغو شود؟"))return;setBusy(true);try{const response=await fetch("/api/property-open-house",{method:"POST",headers:{"content-type":"application/json"},credentials:"same-origin",body:JSON.stringify({action:"cancel",id})});if(!response.ok){const data=await response.json().catch(()=>null) as {statusMessage?:string};throw new Error(data?.statusMessage||"لغو بازدید انجام نشد.");}toast.success("بازدید گروهی لغو شد.");await load();}catch(error){toast.error(error instanceof Error?error.message:"لغو بازدید انجام نشد.");}finally{setBusy(false);}}
 const activeRsvps=rsvps.filter(x=>x.status!=="cancelled");
 return <section className="admin-section admin-property-open-house" aria-label="بازدید گروهی فایل"><div className="admin-property-feature-head"><div><span className="kicker">فروش و بازدید</span><h3><CalendarClock size={18}/> اوپن‌هاوس و بازدید گروهی</h3><p>برای این فایل زمان مشخص و ظرفیت تعریف کنید و ثبت‌نام مشتریان را مدیریت کنید.</p></div><button type="button" className="btn-ghost" onClick={()=>void load()} disabled={loading}><RefreshCw size={15}/> بروزرسانی</button></div><div className="admin-open-house-create"><label><span>شروع</span><PersianDateTimePicker value={startsAt} onChange={setStartsAt} title="شروع اوپن‌هاوس" hint="" /></label><label><span>پایان</span><PersianDateTimePicker value={endsAt} onChange={setEndsAt} title="پایان اوپن‌هاوس" hint="" /></label><label><span>ظرفیت نفر</span><input dir="ltr" inputMode="numeric" value={capacity} onChange={e=>setCapacity(e.target.value.replace(/\D/g,"").slice(0,3))}/></label><label className="admin-open-house-wide"><span>توضیح برای مشتری</span><input value={note} onChange={e=>setNote(e.target.value.slice(0,500))} placeholder="مثلاً بازدید با هماهنگی قبلی"/></label><button type="button" className="btn-gold" onClick={()=>void createEvent()} disabled={busy}><CalendarClock size={16}/> ثبت زمان بازدید</button></div><div className="admin-property-feature-list">{loading&&!items.length?<div className="admin-empty">در حال دریافت زمان‌های بازدید…</div>:!items.length?<div className="admin-empty">هنوز زمان اوپن‌هاوسی برای این فایل ثبت نشده است.</div>:items.map(item=><article key={item.id} className="admin-property-feature-row"><div className="admin-property-feature-row-main"><div className="admin-property-feature-row-meta"><span>{item.status==="scheduled"?"فعال":"لغوشده"}</span><small>{faDate(item.startsAt)}</small></div><strong>{item.remainingSeats.toLocaleString("fa-IR")} جای خالی از {item.capacity.toLocaleString("fa-IR")}</strong>{item.note?<small>{item.note}</small>:null}</div>{item.status==="scheduled"?<button type="button" className="btn-ghost" onClick={()=>void cancel(item.id)} disabled={busy}><Trash2 size={14}/> لغو زمان</button>:null}</article>)}</div><div className="admin-open-house-rsvps"><div className="admin-property-feature-head"><div><span className="kicker">ثبت‌نام‌ها</span><h3><UsersRound size={17}/> مراجعان ثبت‌نام‌شده</h3></div><strong>{activeRsvps.reduce((sum,item)=>sum+item.partySize,0).toLocaleString("fa-IR")} نفر</strong></div>{!activeRsvps.length?<p className="admin-open-house-rsvps-empty">هنوز ثبت‌نامی برای بازدیدهای این فایل وجود ندارد.</p>:<div className="admin-open-house-rsvp-list">{activeRsvps.map(item=><div className="admin-open-house-rsvp" key={item.id}><div><strong>{item.name}</strong><small>{item.phone} · {item.partySize.toLocaleString("fa-IR")} نفر</small></div><span>{faDate(item.createdAt)}</span>{item.note?<p>{item.note}</p>:null}</div>)}</div>}</div></section>;
}
