import { useEffect, useState } from "react";
import { BarChart3, Plus, RefreshCw, Save, Target, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { listAdminConsultants, type Consultant } from "@/lib/consultants";
import { formatToman } from "@/lib/money";

type Row = {
  id: string | null; consultant: string; leadTarget: number; contractTarget: number; volumeTarget: number; commissionTarget: number;
  leads: number; contracts: number; deals: number; volume: number; commissions: number; note: string;
};
const monthNow=()=>{const d=new Date();return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0");};
const fa=(n:number)=>n.toLocaleString("fa-IR");
const pct=(a:number,b:number)=>b>0?Math.min(100,Math.round(a/b*100)):0;

export function AdminConsultantTargets(){
 const [month,setMonth]=useState(monthNow()),[rows,setRows]=useState<Row[]>([]),[consultants,setConsultants]=useState<Consultant[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 const [form,setForm]=useState({consultant:"",leadTarget:"",contractTarget:"",volumeTarget:"",commissionTarget:"",note:""});
 const load=async()=>{setLoading(true);try{const [r,team]=await Promise.all([
   fetch("/api/admin-consultant-targets",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"list",month})}),
   listAdminConsultants()
 ]);const data=await r.json();if(!r.ok)throw new Error(data?.statusMessage||"اهداف مشاوران دریافت نشد.");setRows(data.rows||[]);setConsultants(team);if(!form.consultant&&team[0])setForm(v=>({...v,consultant:team[0].name}));}catch(e){toast.error(e instanceof Error?e.message:"اهداف دریافت نشد.");}finally{setLoading(false);}};
 useEffect(()=>{void load();},[month]);
 async function save(){if(!form.consultant.trim())return toast.error("مشاور را انتخاب کنید.");setSaving(true);try{const r=await fetch("/api/admin-consultant-targets",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"save",month,...form})});const x=await r.json();if(!r.ok)throw new Error(x?.statusMessage||"ذخیره هدف انجام نشد.");toast.success("هدف ماهانه ذخیره شد.");setForm(v=>({...v,leadTarget:"",contractTarget:"",volumeTarget:"",commissionTarget:"",note:""}));await load();}catch(e){toast.error(e instanceof Error?e.message:"ذخیره هدف انجام نشد.");}finally{setSaving(false);}}
 async function remove(id:string){if(!window.confirm("هدف این مشاور حذف شود؟"))return;const r=await fetch("/api/admin-consultant-targets",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"delete",id})});if(r.ok){toast.success("هدف حذف شد.");await load();}}
 const totals=rows.reduce((a,r)=>({leadTarget:a.leadTarget+r.leadTarget,contractTarget:a.contractTarget+r.contractTarget,volumeTarget:a.volumeTarget+r.volumeTarget,commissionTarget:a.commissionTarget+r.commissionTarget,leads:a.leads+r.leads,contracts:a.contracts+r.contracts,volume:a.volume+r.volume,commissions:a.commissions+r.commissions}),{leadTarget:0,contractTarget:0,volumeTarget:0,commissionTarget:0,leads:0,contracts:0,volume:0,commissions:0});
 return <section className="admin-panel admin-consultant-targets" dir="rtl">
  <div className="admin-panel-head"><div><span className="kicker">مدیریت تیم</span><h2><Target size={18}/> اهداف ماهانه مشاوران</h2><p>برای هر مشاور هدف لید، قرارداد، حجم معامله و کمیسیون تعیین کنید و نتیجه واقعی همان ماه را کنار آن ببینید.</p></div><div className="admin-target-toolbar"><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/><button className="btn-ghost" type="button" onClick={()=>void load()} disabled={loading}><RefreshCw size={14}/> بروزرسانی</button></div></div>
  <div className="admin-kpi-cards admin-performance-kpis"><div className="admin-kpi-card"><span>هدف لید</span><strong>{fa(totals.leadTarget)}</strong></div><div className="admin-kpi-card"><span>لید واقعی</span><strong>{fa(totals.leads)}</strong></div><div className="admin-kpi-card"><span>هدف قرارداد</span><strong>{fa(totals.contractTarget)}</strong></div><div className="admin-kpi-card"><span>قرارداد واقعی</span><strong>{fa(totals.contracts)}</strong></div><div className="admin-kpi-card"><span>هدف حجم معاملات</span><strong>{formatToman(totals.volumeTarget)}</strong></div><div className="admin-kpi-card"><span>حجم واقعی</span><strong>{formatToman(totals.volume)}</strong></div></div>
  <div className="admin-target-form"><label className="field"><span>مشاور</span><select value={form.consultant} onChange={e=>setForm(v=>({...v,consultant:e.target.value}))}>{consultants.map(c=><option key={c.id} value={c.name}>{c.name}</option>)}</select></label><label className="field"><span>هدف لید</span><input inputMode="numeric" value={form.leadTarget} onChange={e=>setForm(v=>({...v,leadTarget:e.target.value}))}/></label><label className="field"><span>هدف قرارداد</span><input inputMode="numeric" value={form.contractTarget} onChange={e=>setForm(v=>({...v,contractTarget:e.target.value}))}/></label><label className="field"><span>هدف حجم معاملات</span><input inputMode="numeric" value={form.volumeTarget} onChange={e=>setForm(v=>({...v,volumeTarget:e.target.value}))}/></label><label className="field"><span>هدف کمیسیون</span><input inputMode="numeric" value={form.commissionTarget} onChange={e=>setForm(v=>({...v,commissionTarget:e.target.value}))}/></label><button className="btn-gold" type="button" onClick={()=>void save()} disabled={saving}><Save size={15}/>{saving?"در حال ذخیره…":"ذخیره هدف"}</button></div>
  {loading?<div className="admin-empty">در حال محاسبه…</div>:!rows.length?<div className="admin-empty"><Target size={24}/><strong>هنوز هدفی برای این ماه ثبت نشده است.</strong></div>:<div className="admin-target-table-wrap"><table className="admin-target-table"><thead><tr><th>مشاور</th><th>لید</th><th>قرارداد</th><th>حجم معامله</th><th>کمیسیون</th><th>عملیات</th></tr></thead><tbody>{rows.map(r=><tr key={r.consultant}><td><strong>{r.consultant}</strong></td><td><b>{fa(r.leads)} / {fa(r.leadTarget)}</b><span className="admin-target-progress"><i style={{width:pct(r.leads,r.leadTarget)+"%"}}/></span></td><td><b>{fa(r.contracts)} / {fa(r.contractTarget)}</b><span className="admin-target-progress"><i style={{width:pct(r.contracts,r.contractTarget)+"%"}}/></span></td><td><b>{formatToman(r.volume)} / {formatToman(r.volumeTarget)}</b></td><td><b>{formatToman(r.commissions)} / {formatToman(r.commissionTarget)}</b></td><td>{r.id?<button className="admin-icon-btn danger" type="button" onClick={()=>void remove(r.id)} title="حذف"><Trash2 size={14}/></button>:null}</td></tr>)}</tbody></table></div>}
 </section>;
}
