import { useCallback, useEffect, useState } from "react";
import { AlertCircle, CalendarDays, Phone, RefreshCw } from "lucide-react";
import { toast } from "sonner";
import "./admin-agenda.css";

type AgendaData = {
  overdueFollowUps: Array<{ id:string; name:string; phone:string; deal:string; neighborhood:string; consultant:string; status:string; followUpAt:string; overdue:boolean }>;
  upcomingVisits: Array<{ id:string; name:string; phone:string; deal:string; neighborhood:string; consultant:string; visitStatus:string; visitPreferredAt:string }>;
  upcomingCallbacks: Array<{ id:string; name:string; phone:string; deal:string; neighborhood:string; consultant:string; callbackPreferredAt:string }>;
};

function formatDate(value:string){ try{return new Intl.DateTimeFormat("fa-IR-u-ca-persian",{dateStyle:"short",timeStyle:"short",timeZone:"Asia/Tehran"}).format(new Date(value));}catch{return value;} }

function AgendaRow({name,phone,label,detail,tone,date,onOpenLeads}:{name:string;phone:string;label:string;detail:string;tone:"danger"|"gold";date:string;onOpenLeads:()=>void}){
  return <div className="admin-agenda-row"><span className="admin-agenda-icon" data-tone={tone}>{tone==="danger"?<AlertCircle size={16}/>:<CalendarDays size={16}/>}</span><div className="admin-agenda-main"><div className="admin-agenda-head"><strong>{name}</strong><span>{label}</span></div><p>{detail}</p><small>{formatDate(date)}</small></div><div className="admin-agenda-actions">{phone?<a href={"tel:"+phone} title="تماس"><Phone size={15}/></a>:null}<button type="button" onClick={onOpenLeads}>لید</button></div></div>;
}

export function AdminAgenda({onOpenLeads}:{onOpenLeads:()=>void}){
  const [data,setData]=useState<AgendaData|null>(null); const [loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);try{const response=await fetch("/api/admin-agenda",{method:"POST",headers:{"content-type":"application/json"},body:"{}"});const payload=await response.json().catch(()=>null) as (AgendaData & {statusMessage?:string})|null;if(!response.ok)throw new Error(payload?.statusMessage||"دستورکار امروز بارگذاری نشد.");setData({overdueFollowUps:Array.isArray(payload?.overdueFollowUps)?payload.overdueFollowUps:[],upcomingVisits:Array.isArray(payload?.upcomingVisits)?payload.upcomingVisits:[],upcomingCallbacks:Array.isArray(payload?.upcomingCallbacks)?payload.upcomingCallbacks:[]});}catch(error){toast.error(error instanceof Error?error.message:"دستورکار امروز بارگذاری نشد.");setData({overdueFollowUps:[],upcomingVisits:[],upcomingCallbacks:[]});}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),60000);return()=>window.clearInterval(timer);},[load]);
  const overdue=data?.overdueFollowUps.filter((item)=>item.overdue)??[]; const upcoming=data?.upcomingVisits??[]; const callbacks=data?.upcomingCallbacks??[];
  return <section className="admin-agenda admin-panel" aria-label="دستورکار امروز"><div className="admin-panel-head"><div><span className="kicker">دستورکار</span><h2>کارهای مهم امروز</h2><p className="admin-agenda-subtitle">پیگیری‌های عقب‌افتاده و بازدیدهای ۷ روز آینده در یک نگاه.</p></div><button type="button" className="btn-ghost" onClick={()=>void load()} disabled={loading}><RefreshCw size={15} className={loading?"admin-spin":undefined}/> بروزرسانی</button></div>{loading&&!data?<div className="admin-agenda-empty">در حال دریافت دستورکار…</div>:!overdue.length&&!upcoming.length&&!callbacks.length?<div className="admin-agenda-empty">در حال حاضر مورد فوری یا بازدید زمان‌بندی‌شده‌ای ثبت نشده است.</div>:<div className="admin-agenda-grid"><div><div className="admin-agenda-column-head" data-tone="danger"><AlertCircle size={15}/><strong>پیگیری عقب‌افتاده</strong><span>{overdue.length.toLocaleString("fa-IR")}</span></div><div className="admin-agenda-list">{overdue.map((item)=><AgendaRow key={item.id} name={item.name} phone={item.phone} label="پیگیری معوق" detail={`${item.deal}${item.neighborhood?" · "+item.neighborhood:""}${item.consultant?" · "+item.consultant:""}`} tone="danger" date={item.followUpAt} onOpenLeads={onOpenLeads}/>)}</div></div><div><div className="admin-agenda-column-head" data-tone="gold"><CalendarDays size={15}/><strong>بازدیدهای پیش‌رو</strong><span>{upcoming.length.toLocaleString("fa-IR")}</span></div><div className="admin-agenda-list">{upcoming.map((item)=><AgendaRow key={item.id} name={item.name} phone={item.phone} label={item.visitStatus==="confirmed"?"تأییدشده":"درخواست‌شده"} detail={`${item.deal}${item.neighborhood?" · "+item.neighborhood:""}${item.consultant?" · "+item.consultant:""}`} tone="gold" date={item.visitPreferredAt} onOpenLeads={onOpenLeads}/>)}</div></div><div><div className="admin-agenda-column-head" data-tone="gold"><Phone size={15}/><strong>تماس‌های زمان‌بندی‌شده</strong><span>{callbacks.length.toLocaleString("fa-IR")}</span></div><div className="admin-agenda-list">{callbacks.map((item)=><AgendaRow key={item.id} name={item.name} phone={item.phone} label="تماس برنامه‌ریزی‌شده" detail={`${item.deal}${item.neighborhood?" · "+item.neighborhood:""}${item.consultant?" · "+item.consultant:""}`} tone="gold" date={item.callbackPreferredAt} onOpenLeads={onOpenLeads}/>)}</div></div></div>}</section>;
}
