import { useCallback, useEffect, useState, type ChangeEvent } from "react";
import { Check, FileText, Loader2, RefreshCw, Trash2, Upload, XCircle } from "lucide-react";
import { toast } from "sonner";
import { uploadInChunks } from "@/lib/media-upload-client";
import { adminErrorMessage } from "@/components/hirmand/admin-ui-utils";
const STAGES=[["qualification","ارزیابی اولیه"],["property_selection","انتخاب فایل"],["viewing","بازدید"],["negotiation","مذاکره"],["contract_preparation","آماده‌سازی قرارداد"],["contract_signed","قرارداد امضا شد"],["won","موفق"],["lost","بسته‌شده"]] as const;
const DOC_TYPES:Record<string,string>={identity:"مدارک هویتی",ownership:"مدرک مالکیت",property:"مدارک ملک",bank:"مدارک بانکی",contract:"قرارداد",receipt:"رسید",other:"سایر"};
type Lead={id:string;name:string;phone:string;status:string;deal:string;neighborhood:string;consultant:string;dealStage:string;followUpAt:string|null;propertySlug:string|null;propertyTitle:string};
type Document={id:string;leadId:string|null;propertyId:string|null;leadName:string;propertyTitle:string;title:string;documentType:string;status:string;fileUrl:string;fileName:string;mimeType:string;sizeBytes:number;notes:string;dueAt:string|null;createdAt:string;updatedAt:string};
type Data={generatedAt:string;stages:Record<string,number>;leads:Lead[];documents:Document[]};
const CSS=[".adoc{display:grid;gap:13px;margin-bottom:18px}",".adoc-head{display:flex;justify-content:space-between;gap:10px;align-items:flex-start;flex-wrap:wrap}.adoc-head h2{margin:0;color:var(--navy-900);font-size:1rem}.adoc-head p{margin:4px 0 0;color:var(--muted);font-size:.68rem}",".adoc-tabs{display:flex;gap:6px;flex-wrap:wrap}.adoc-tabs button{border:1px solid var(--line);background:var(--card-2);color:var(--muted);padding:8px 11px;border-radius:9px;font-size:.68rem}.adoc-tabs button[data-active='1']{background:var(--navy-900);color:#fff;border-color:var(--navy-900)}",".adoc-pipeline{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}.adoc-stage{padding:11px 12px;border:1px solid var(--line);border-radius:10px;background:var(--card)}.adoc-stage small{display:block;color:var(--muted);font-size:.62rem}.adoc-stage strong{display:block;margin-top:4px;color:var(--navy-900);font-size:1rem}",".adoc-list{display:grid;gap:8px}.adoc-lead{display:grid;grid-template-columns:minmax(0,1fr) minmax(220px,.8fr) auto;gap:10px;align-items:center;padding:10px 12px;border:1px solid var(--line);border-radius:10px;background:var(--card)}.adoc-lead strong{color:var(--navy-900);font-size:.75rem}.adoc-meta{display:flex;flex-wrap:wrap;gap:5px;margin-top:4px}.adoc-chip{padding:4px 6px;border:1px solid var(--line);border-radius:999px;background:var(--card-2);color:var(--subtle);font-size:.61rem}",".adoc-doc-form{display:grid;grid-template-columns:minmax(180px,.8fr) minmax(180px,1fr) minmax(150px,.6fr) minmax(180px,1fr);gap:8px;align-items:end;padding:12px;border:1px dashed var(--line-2);border-radius:10px;background:var(--card-2)}",".adoc-doc-row{display:grid;grid-template-columns:minmax(0,1fr) minmax(160px,.5fr) auto;gap:8px;align-items:center;padding:10px 12px;border:1px solid var(--line);border-radius:10px;background:var(--card)}.adoc-doc-row strong{color:var(--navy-900);font-size:.73rem}.adoc-doc-row small{display:block;color:var(--muted);font-size:.61rem;margin-top:2px}",".adoc-doc-actions{display:flex;gap:5px;flex-wrap:wrap}.adoc-doc-actions a,.adoc-doc-actions button{padding:6px 8px;border-radius:8px;font-size:.61rem}.adoc-upload-progress{height:5px;border-radius:999px;background:var(--line);overflow:hidden}.adoc-upload-progress span{display:block;height:100%;background:var(--brass-500)}","@media(max-width:1000px){.adoc-pipeline{grid-template-columns:repeat(2,1fr)}.adoc-lead{grid-template-columns:1fr}.adoc-doc-form{grid-template-columns:1fr 1fr}.adoc-doc-row{grid-template-columns:1fr}}","@media(max-width:560px){.adoc-pipeline,.adoc-doc-form{grid-template-columns:1fr}.adoc-tabs{overflow:auto;flex-wrap:nowrap;padding-bottom:2px}.adoc-tabs button{white-space:nowrap}}"].join("\\n");
function fmt(v:string|null){return v?new Date(v).toLocaleString("fa-IR",{dateStyle:"short",timeStyle:"short"}):"—";}
function sizeLabel(bytes:number){if(bytes>=1024*1024)return(bytes/1024/1024).toLocaleString("fa-IR",{maximumFractionDigits:1})+" مگابایت";if(bytes>=1024)return Math.round(bytes/1024).toLocaleString("fa-IR")+" کیلوبایت";return bytes.toLocaleString("fa-IR")+" بایت";}
export function AdminDealDocumentsCenter(){
  const [data,setData]=useState<Data|null>(null),[tab,setTab]=useState<"deals"|"documents">("deals"),[loading,setLoading]=useState(true),[saving,setSaving]=useState(""),[leadId,setLeadId]=useState(""),[title,setTitle]=useState(""),[type,setType]=useState("other"),[notes,setNotes]=useState(""),[file,setFile]=useState<File|null>(null),[progress,setProgress]=useState(0);
  const load=useCallback(async()=>{setLoading(true);try{const res=await fetch("/api/admin-deals-documents",{method:"POST",headers:{"content-type":"application/json"},credentials:"same-origin",body:JSON.stringify({action:"summary"})});const body=await res.json().catch(()=>({})) as Data&{statusMessage?:string};if(!res.ok)throw new Error(body.statusMessage||"مرکز معامله و اسناد بارگذاری نشد.");setData(body);}catch(e){toast.error(adminErrorMessage(e,"مرکز معامله و اسناد بارگذاری نشد."));}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  async function stage(lead:Lead,next:string){setSaving("stage:"+lead.id);try{const res=await fetch("/api/admin-deals-documents",{method:"POST",headers:{"content-type":"application/json"},credentials:"same-origin",body:JSON.stringify({action:"stage",leadId:lead.id,stage:next})});const body=await res.json().catch(()=>({})) as {statusMessage?:string};if(!res.ok)throw new Error(body.statusMessage||"مرحله ذخیره نشد.");await load();}catch(e){toast.error(adminErrorMessage(e,"مرحله ذخیره نشد."));}finally{setSaving("");}}
  async function docStatus(doc:Document,next:string){setSaving("doc:"+doc.id);try{const res=await fetch("/api/admin-deals-documents",{method:"POST",headers:{"content-type":"application/json"},credentials:"same-origin",body:JSON.stringify({action:"document_status",documentId:doc.id,status:next})});const body=await res.json().catch(()=>({})) as {statusMessage?:string};if(!res.ok)throw new Error(body.statusMessage||"وضعیت سند ذخیره نشد.");await load();toast.success("وضعیت سند به‌روزرسانی شد.");}catch(e){toast.error(adminErrorMessage(e,"وضعیت سند ذخیره نشد."));}finally{setSaving("");}}
  async function removeDoc(doc:Document){if(!window.confirm("این سند و فایل ذخیره‌شده حذف شود؟"))return;setSaving("delete:"+doc.id);try{const res=await fetch("/api/admin-deals-documents",{method:"POST",headers:{"content-type":"application/json"},credentials:"same-origin",body:JSON.stringify({action:"delete_document",documentId:doc.id})});const body=await res.json().catch(()=>({})) as {statusMessage?:string};if(!res.ok)throw new Error(body.statusMessage||"حذف سند انجام نشد.");await load();toast.success("سند حذف شد.");}catch(e){toast.error(adminErrorMessage(e,"حذف سند انجام نشد."));}finally{setSaving("");}}
  async function uploadDocument(){if(!leadId||!title.trim()||!file){toast.error("لید، عنوان سند و فایل را مشخص کنید.");return;}if(file.size>12*1024*1024){toast.error("حجم سند باید حداکثر ۱۲ مگابایت باشد.");return;}if(!["application/pdf","image/jpeg","image/png","image/webp"].includes(file.type)){toast.error("فقط PDF، JPG، PNG و WebP مجاز است.");return;}setSaving("upload");setProgress(0);try{const result=await uploadInChunks({endpoint:"/api/admin-document-upload",file,contentType:file.type,payload:{title:title.trim(),artist:JSON.stringify({leadId,documentType:type,notes:notes.trim()})},onProgress:setProgress});if(!result.response.document)throw new Error("اطلاعات سند از سرور دریافت نشد.");setTitle("");setNotes("");setFile(null);setLeadId("");setType("other");await load();toast.success("سند با موفقیت ثبت شد.");}catch(e){toast.error(adminErrorMessage(e,"آپلود و ثبت سند انجام نشد."));}finally{setSaving("");setProgress(0);}}
  function onFile(e:ChangeEvent<HTMLInputElement>){setFile(e.target.files?.[0]??null);}
  return <section className="admin-panel adoc"><style>{CSS}</style><div className="adoc-head"><div><span className="kicker">Deal & Documents Center</span><h2>مرکز معامله و اسناد</h2><p>مراحل معامله از وضعیت CRM جداست؛ اسناد حساس نیز فقط از مسیر مدیریتی قابل دریافت هستند.</p></div><button className="btn-ghost" type="button" onClick={()=>void load()} disabled={loading}><RefreshCw size={15} className={loading?"admin-spin":undefined}/>به‌روزرسانی</button></div>
    <div className="adoc-tabs"><button type="button" data-active={tab==="deals"?"1":"0"} onClick={()=>setTab("deals")}>مراحل معامله</button><button type="button" data-active={tab==="documents"?"1":"0"} onClick={()=>setTab("documents")}>اسناد · {(data?.documents.length??0).toLocaleString("fa-IR")}</button></div>
    {tab==="deals"?<><div className="adoc-pipeline">{STAGES.map(([key,label])=><div className="adoc-stage" key={key}><small>{label}</small><strong>{(data?.stages[key]??0).toLocaleString("fa-IR")}</strong></div>)}</div><div className="adoc-list">{(data?.leads??[]).map(lead=><article className="adoc-lead" key={lead.id}><div><strong>{lead.name||"بدون نام"}</strong><div className="adoc-meta"><span className="adoc-chip">{lead.phone}</span><span className="adoc-chip">{lead.deal||"نامشخص"}</span><span className="adoc-chip">{lead.consultant||"بدون مشاور"}</span>{lead.neighborhood?<span className="adoc-chip">{lead.neighborhood}</span>:null}</div>{lead.propertyTitle?<div className="adoc-meta"><span className="adoc-chip">{lead.propertyTitle}</span></div>:null}</div><label className="field"><span>مرحله معامله</span><select value={lead.dealStage} disabled={saving==="stage:"+lead.id} onChange={e=>void stage(lead,e.target.value)}>{STAGES.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><div className="adoc-meta"><span className="adoc-chip">پیگیری: {fmt(lead.followUpAt)}</span>{lead.propertySlug?<a className="btn-ghost" href={"/properties/"+encodeURIComponent(lead.propertySlug)} target="_blank" rel="noreferrer">ملک</a>:null}<button className="btn-ghost" type="button" onClick={()=>{setTab("documents");setLeadId(lead.id);}}><FileText size={13}/>سند</button></div></article>)}</div></>
    :<><div className="adoc-doc-form"><label className="field"><span>لید</span><select value={leadId} onChange={e=>setLeadId(e.target.value)}><option value="">انتخاب لید…</option>{(data?.leads??[]).map(lead=><option key={lead.id} value={lead.id}>{lead.name||"بدون نام"} · {lead.phone}</option>)}</select></label><label className="field"><span>عنوان سند</span><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="مثلاً سند مالکیت یا کارت ملی"/></label><label className="field"><span>نوع</span><select value={type} onChange={e=>setType(e.target.value)}>{Object.entries(DOC_TYPES).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label className="field"><span>فایل</span><input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" onChange={onFile}/></label><label className="field" style={{gridColumn:"1/-1"}}><span>توضیح داخلی</span><textarea rows={2} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="مثلاً اصل سند بررسی شد…"/></label><div style={{display:"grid",gap:6}}><button className="btn-gold" type="button" onClick={()=>void uploadDocument()} disabled={saving==="upload"||!leadId||!title.trim()||!file}>{saving==="upload"?<><Loader2 size={15} className="admin-spin"/>در حال آپلود {progress.toLocaleString("fa-IR")}٪</>:<><Upload size={15}/>ثبت سند</>}</button>{saving==="upload"?<div className="adoc-upload-progress"><span style={{width:progress+"%"}}/></div>:null}</div></div>
      <div className="adoc-list">{(data?.documents??[]).map(doc=><article className="adoc-doc-row" key={doc.id}><div><strong>{doc.title}</strong><small>{DOC_TYPES[doc.documentType]||doc.documentType} · {doc.leadName||doc.propertyTitle||"بدون اتصال"} · {sizeLabel(doc.sizeBytes)} · {fmt(doc.createdAt)}</small>{doc.notes?<small>{doc.notes}</small>:null}</div><div><span className="adoc-chip">{doc.status==="verified"?"تأیید شده":doc.status==="rejected"?"رد شده":"در انتظار"}</span></div><div className="adoc-doc-actions"><a className="btn-ghost" href={doc.fileUrl} target="_blank" rel="noreferrer"><FileText size={12}/>دریافت</a>{doc.status!=="verified"?<button className="btn-ghost" type="button" onClick={()=>void docStatus(doc,"verified")} disabled={Boolean(saving)}><Check size={12}/>تأیید</button>:null}{doc.status!=="rejected"?<button className="btn-ghost" type="button" onClick={()=>void docStatus(doc,"rejected")} disabled={Boolean(saving)}><XCircle size={12}/>رد</button>:null}<button className="btn-ghost danger" type="button" onClick={()=>void removeDoc(doc)} disabled={Boolean(saving)}><Trash2 size={12}/>حذف</button></div></article>)}{!data?.documents.length&&!loading?<div className="admin-empty">هنوز سندی ثبت نشده است.</div>:null}</div></>}
  </section>;
}
