import { AlertCircle, ArrowLeft, CheckCircle2, FileCheck2, RefreshCw, UserRound } from "lucide-react";
import { useState } from "react";
import { Link } from "@tanstack/react-router";
import { toast } from "sonner";
import { SITE } from "@/lib/site";
import "@/property-feature-enhancements.css";
type OwnerStatus={trackingToken:string;status:string;statusLabel:string;reviewNote:string;createdAt:string;updatedAt:string;reviewedAt:string|null;consultant:string;property:{title:string;slug:string}|null;timeline:Array<{type:string;label:string;note:string;at:string}>;};
function normalizeCode(value:string){return value.toUpperCase().replace(/\s+/g,"").slice(0,23);}
function faDate(value:string){try{return new Intl.DateTimeFormat("fa-IR",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Tehran"}).format(new Date(value));}catch{return value;}}
export function OwnerPropertyStatus(){
 const[code,setCode]=useState("");const[data,setData]=useState<OwnerStatus|null>(null);const[loading,setLoading]=useState(false);
 async function lookup(){const normalized=normalizeCode(code);if(!/^HIR-[A-Z0-9]{2}-[A-F0-9]{12}$/.test(normalized)){toast.error("کد رهگیری ثبت ملک معتبر نیست.");return;}setLoading(true);try{const response=await fetch("/api/owner-property-status",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({trackingToken:normalized})});const payload=await response.json().catch(()=>null) as OwnerStatus&{statusMessage?:string};if(!response.ok)throw new Error(payload?.statusMessage||"وضعیت پرونده دریافت نشد.");setData(payload);}catch(error){setData(null);toast.error(error instanceof Error?error.message:"وضعیت پرونده دریافت نشد.");}finally{setLoading(false);}}
 return <section className="owner-property-status" aria-labelledby="owner-property-status-title"><div className="owner-property-status-head"><div><span className="kicker">مرکز مالک</span><h2 id="owner-property-status-title">پیگیری ثبت ملک توسط مالک</h2><p>با کد رهگیری ببینید پرونده در چه مرحله‌ای است، آیا اصلاح لازم دارد و ملک چه زمانی وارد فایل‌های منتشرشده شده است.</p></div><div className="owner-property-status-icon"><FileCheck2 size={26}/></div></div><form className="owner-property-status-form" onSubmit={e=>{e.preventDefault();void lookup();}}><label><span>کد رهگیری ثبت ملک</span><input dir="ltr" value={code} onChange={e=>setCode(normalizeCode(e.target.value))} placeholder="HIR-26-XXXXXXXXXXXX" maxLength={23} autoComplete="off"/></label><button type="submit" className="btn-gold" disabled={loading}><RefreshCw size={15} className={loading?"owner-property-status-spin":undefined}/>{loading?"در حال بررسی…":"بررسی وضعیت"}</button></form>{data?<article className="owner-property-status-result"><div className="owner-property-status-summary"><div className={"owner-property-status-pill is-"+data.status}>{data.status==="approved"?<CheckCircle2 size={15}/>:data.status==="rejected"?<AlertCircle size={15}/>:<RefreshCw size={15}/>} {data.statusLabel}</div><div className="owner-property-status-meta"><span>آخرین بروزرسانی: {faDate(data.updatedAt)}</span>{data.consultant?<span><UserRound size={14}/>مشاور: {data.consultant}</span>:null}</div></div>{data.reviewNote?<div className="owner-property-status-note"><strong><AlertCircle size={15}/> نیاز به اصلاح</strong><p>{data.reviewNote}</p><a className="btn-ghost" href={"/submit-property?code=" + encodeURIComponent(data.trackingToken)}>اصلاح اطلاعات و ارسال مجدد <ArrowLeft size={14}/></a></div>:null}{data.property?<div className="owner-property-status-property"><div><span className="kicker">فایل عمومی</span><strong>{data.property.title}</strong></div><Link className="btn-gold" to="/properties/$slug" params={{slug:data.property.slug}}>مشاهده فایل</Link></div>:null}{data.timeline.length?<div className="owner-property-status-timeline">{data.timeline.slice(-8).reverse().map((item,index)=><div className="owner-property-status-event" key={item.type+item.at+index}><span><CheckCircle2 size={13}/></span><div><strong>{item.label}</strong><p>{item.note}</p><time>{faDate(item.at)}</time></div></div>)}</div>:null}<small className="owner-property-status-foot">این صفحه فقط وضعیت پرونده را نشان می‌دهد و اطلاعات تماس خصوصی مالک را نمایش نمی‌دهد.</small></article>:null}<div className="owner-property-status-help">{SITE.nameFa} · کد رهگیری را نزد خود نگه دارید تا در دفعات بعد سریع‌تر وضعیت پرونده را ببینید.</div></section>;
}
