import { MessageCircleQuestion, Send, ShieldCheck } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { toast } from "sonner";
import type { Property } from "@/lib/properties";
import "@/property-feature-enhancements.css";

type Question={id:string;question:string;answer:string;createdAt:string;answeredAt:string|null;};
function formatDate(value:string){try{return new Intl.DateTimeFormat("fa-IR",{dateStyle:"medium",timeZone:"Asia/Tehran"}).format(new Date(value));}catch{return value;}}
export function PropertyQuestions({property}:{property:Pick<Property,"id">}){
 const[questions,setQuestions]=useState<Question[]>([]);const[question,setQuestion]=useState("");const[loading,setLoading]=useState(true);const[sending,setSending]=useState(false);
 const load=useCallback(async()=>{setLoading(true);try{const response=await fetch("/api/property-questions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"list",propertyId:property.id})});const data=await response.json().catch(()=>null) as {questions?:Question[]};if(!response.ok)throw new Error("پرسش‌های فایل دریافت نشد.");setQuestions(Array.isArray(data?.questions)?data.questions:[]);}catch(error){toast.error(error instanceof Error?error.message:"پرسش‌های فایل دریافت نشد.");}finally{setLoading(false);}},[property.id]);
 useEffect(()=>{void load();},[load]);
 async function submit(){const value=question.trim();if(value.length<8){toast.error("سؤال را کامل‌تر بنویسید.");return;}setSending(true);try{const response=await fetch("/api/property-questions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"ask",propertyId:property.id,question:value})});const data=await response.json().catch(()=>null) as {message?:string;statusMessage?:string};if(!response.ok)throw new Error(data?.statusMessage||data?.message||"ثبت سؤال انجام نشد.");setQuestion("");toast.success(data?.message||"سؤال ثبت شد.");}catch(error){toast.error(error instanceof Error?error.message:"ثبت سؤال انجام نشد.");}finally{setSending(false);}}
 return <section id="property-questions" className="property-public-questions" aria-labelledby="property-questions-title"><header className="property-public-questions-head"><div><span className="kicker">سؤال از مشاور</span><h2 id="property-questions-title">پرسش‌وپاسخ این فایل</h2><p>سؤال‌های واقعی مشتریان و پاسخ مشاور هیرمند را اینجا ببینید.</p></div><span className="property-public-questions-badge"><ShieldCheck size={15}/> پاسخ پس از بررسی نمایش داده می‌شود</span></header><div className="property-public-questions-list">{loading?<div className="property-public-questions-empty">در حال دریافت پاسخ‌ها…</div>:!questions.length?<div className="property-public-questions-empty">هنوز پرسش پاسخ‌داده‌شده‌ای برای این فایل ثبت نشده است.</div>:questions.map(item=><article key={item.id} className="property-public-question"><div className="property-public-question-q"><MessageCircleQuestion size={17}/><div><span>سؤال</span><p>{item.question}</p></div></div><div className="property-public-question-a"><strong>پاسخ هیرمند</strong><p>{item.answer}</p><time>{formatDate(item.answeredAt||item.createdAt)}</time></div></article>)}</div><div className="property-public-questions-form"><label className="property-public-question-input"><span>سؤال شما درباره این فایل</span><textarea value={question} onChange={e=>setQuestion(e.target.value.slice(0,600))} rows={4} maxLength={600} placeholder="مثلاً شرایط تخفیف، موقعیت دقیق، طبقه یا وضعیت پارکینگ…"/><small>{question.length.toLocaleString("fa-IR")} / ۶۰۰</small></label><button type="button" className="btn-gold" onClick={()=>void submit()} disabled={sending}><Send size={16}/>{sending?"در حال ثبت…":"ارسال سؤال"}</button></div></section>;
}
