import { CalendarClock, CheckCircle2, UsersRound } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { toast } from "sonner";
import type { Property } from "@/lib/properties";
import "@/property-feature-enhancements.css";

type EventItem={id:string;startsAt:string;endsAt:string;capacity:number;bookedSeats:number;remainingSeats:number;note:string;};
function digits(value:string){return value.replace(/[۰-۹]/g,d=>String("۰۱۲۳۴۵۶۷۸۹".indexOf(d))).replace(/[٠-٩]/g,d=>String("٠١٢٣٤٥٦٧٨٩".indexOf(d)));}
function formatDate(value:string){try{return new Intl.DateTimeFormat("fa-IR",{dateStyle:"full",timeStyle:"short",timeZone:"Asia/Tehran"}).format(new Date(value));}catch{return value;}}
export function PropertyOpenHouse({property}:{property:Pick<Property,"id">}){
 const[events,setEvents]=useState<EventItem[]>([]);const[selected,setSelected]=useState<EventItem|null>(null);const[loading,setLoading]=useState(true);const[sending,setSending]=useState(false);
 const[name,setName]=useState("");const[phone,setPhone]=useState("");const[partySize,setPartySize]=useState("1");const[note,setNote]=useState("");
 const load=useCallback(async()=>{setLoading(true);try{const response=await fetch("/api/property-open-house",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"list",propertyId:property.id})});const data=await response.json().catch(()=>null) as {events?:EventItem[]};if(!response.ok)throw new Error("بازدیدهای گروهی دریافت نشد.");const next=Array.isArray(data?.events)?data.events:[];setEvents(next);setSelected(cur=>cur&&next.some(x=>x.id===cur.id)?cur:(next[0]||null));}catch(error){toast.error(error instanceof Error?error.message:"بازدیدهای گروهی دریافت نشد.");}finally{setLoading(false);}},[property.id]);
 useEffect(()=>{void load();},[load]);
 async function register(){const cleanPhone=digits(phone).replace(/\D/g,"");const cleanParty=Math.min(10,Math.max(1,Number(digits(partySize))||1));if(name.trim().length<2){toast.error("نام و نام خانوادگی را وارد کنید.");return;}if(!/^09\d{9}$/.test(cleanPhone)){toast.error("شماره موبایل معتبر نیست.");return;}if(!selected){toast.error("یک زمان برای بازدید انتخاب کنید.");return;}setSending(true);try{const response=await fetch("/api/property-open-house",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"rsvp",eventId:selected.id,name:name.trim(),phone:cleanPhone,partySize:cleanParty,note:note.trim()})});const data=await response.json().catch(()=>null) as {message?:string;statusMessage?:string};if(!response.ok)throw new Error(data?.statusMessage||data?.message||"ثبت‌نام انجام نشد.");toast.success(data?.message||"ثبت‌نام انجام شد.");setName("");setPhone("");setNote("");await load();}catch(error){toast.error(error instanceof Error?error.message:"ثبت‌نام انجام نشد.");}finally{setSending(false);}}
 return <section id="property-open-house" className="property-open-house" aria-labelledby="property-open-house-title"><header className="property-open-house-head"><div><span className="kicker">بازدید ویژه</span><h2 id="property-open-house-title">بازدید گروهی و اوپن‌هاوس</h2><p>زمان مشخصی برای بازدید با ظرفیت محدود؛ جای خودتان را پیشاپیش رزرو کنید.</p></div><div className="property-open-house-badge"><CalendarClock size={16}/> ظرفیت محدود</div></header>{loading?<div className="property-open-house-empty">در حال بررسی زمان‌های فعال…</div>:!events.length?<div className="property-open-house-empty">در حال حاضر بازدید گروهی برنامه‌ریزی نشده است. برای بازدید اختصاصی با مشاور تماس بگیرید.</div>:<div className="property-open-house-grid"><div className="property-open-house-events">{events.map(item=><button type="button" key={item.id} className={"property-open-house-event"+(selected?.id===item.id?" is-active":"")} onClick={()=>setSelected(item)}><span className="property-open-house-event-icon"><CalendarClock size={18}/></span><span><strong>{formatDate(item.startsAt)}</strong><small>{item.remainingSeats.toLocaleString("fa-IR")} جای خالی از {item.capacity.toLocaleString("fa-IR")}</small></span></button>)}</div>{selected?<div className="property-open-house-form"><div className="property-open-house-summary"><div><span>زمان</span><strong>{formatDate(selected.startsAt)}</strong></div><div><UsersRound size={15}/><span>ظرفیت باقی‌مانده</span><strong>{selected.remainingSeats.toLocaleString("fa-IR")} نفر</strong></div>{selected.note?<p>{selected.note}</p>:null}</div><div className="property-open-house-fields"><label><span>نام و نام خانوادگی</span><input value={name} onChange={e=>setName(e.target.value)} maxLength={80}/></label><label><span>موبایل</span><input dir="ltr" inputMode="numeric" value={phone} onChange={e=>setPhone(digits(e.target.value).slice(0,11))} maxLength={11}/></label><label><span>تعداد نفرات</span><input dir="ltr" inputMode="numeric" value={partySize} onChange={e=>setPartySize(digits(e.target.value).slice(0,2))}/></label><label className="property-open-house-field-wide"><span>یادداشت اختیاری</span><textarea value={note} onChange={e=>setNote(e.target.value.slice(0,500))} rows={2}/></label></div><button type="button" className="btn-gold" onClick={()=>void register()} disabled={sending||selected.remainingSeats<=0}><CheckCircle2 size={16}/>{sending?"در حال ثبت‌نام…":"رزرو جای بازدید"}</button></div>:null}</div>}</section>;
}
