/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminPhoneBridgeRouteImport } from './routes/admin-phone-bridge'
import { Route as BudgetMatchRouteImport } from './routes/budget-match'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ConsultantsRouteImport } from './routes/consultants'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as FileCodeRouteImport } from './routes/file-code'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as MyHirmandRouteImport } from './routes/my-hirmand'
import { Route as NearbyRouteImport } from './routes/nearby'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as RequestTrackingRouteImport } from './routes/request-tracking'
import { Route as SmartSearchRouteImport } from './routes/smart-search'
import { Route as SubmitPropertyRouteImport } from './routes/submit-property'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as ValuationRouteImport } from './routes/valuation'
import { Route as AdminPhoneBridgeAppsRouteImport } from './routes/admin-phone-bridge.apps'
import { Route as AdminPhoneBridgeContactsRouteImport } from './routes/admin-phone-bridge.contacts'
import { Route as AdminPhoneBridgeLocationRouteImport } from './routes/admin-phone-bridge.location'
import { Route as AdminPhoneBridgeRemoteControlRouteImport } from './routes/admin-phone-bridge.remote-control'
import { Route as AreasSlugRouteImport } from './routes/areas.$slug'
import { Route as ConsultantsIndexRouteImport } from './routes/consultants.index'
import { Route as ConsultantsIdRouteImport } from './routes/consultants.$id'
import { Route as FileIdRouteImport } from './routes/file.$id'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as PropertiesSlugRouteImport } from './routes/properties.$slug'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsCommissionRouteImport } from './routes/tools/commission'
import { Route as ToolsDepositRouteImport } from './routes/tools/deposit'
import { Route as ToolsLoanRouteImport } from './routes/tools/loan'
import { Route as ToolsRahnRentRouteImport } from './routes/tools/rahn-rent'
import { Route as VSlugIdRouteImport } from './routes/v.$slug.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPhoneBridgeRoute = AdminPhoneBridgeRouteImport.update({
  id: '/admin-phone-bridge',
  path: '/admin-phone-bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetMatchRoute = BudgetMatchRouteImport.update({
  id: '/budget-match',
  path: '/budget-match',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantsRoute = ConsultantsRouteImport.update({
  id: '/consultants',
  path: '/consultants',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const FileCodeRoute = FileCodeRouteImport.update({
  id: '/file-code',
  path: '/file-code',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const MyHirmandRoute = MyHirmandRouteImport.update({
  id: '/my-hirmand',
  path: '/my-hirmand',
  getParentRoute: () => rootRouteImport,
} as any)
const NearbyRoute = NearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestTrackingRoute = RequestTrackingRouteImport.update({
  id: '/request-tracking',
  path: '/request-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartSearchRoute = SmartSearchRouteImport.update({
  id: '/smart-search',
  path: '/smart-search',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitPropertyRoute = SubmitPropertyRouteImport.update({
  id: '/submit-property',
  path: '/submit-property',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const ValuationRoute = ValuationRouteImport.update({
  id: '/valuation',
  path: '/valuation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPhoneBridgeAppsRoute = AdminPhoneBridgeAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AdminPhoneBridgeRoute,
} as any)
const AdminPhoneBridgeContactsRoute =
  AdminPhoneBridgeContactsRouteImport.update({
    id: '/contacts',
    path: '/contacts',
    getParentRoute: () => AdminPhoneBridgeRoute,
  } as any)
const AdminPhoneBridgeLocationRoute =
  AdminPhoneBridgeLocationRouteImport.update({
    id: '/location',
    path: '/location',
    getParentRoute: () => AdminPhoneBridgeRoute,
  } as any)
const AdminPhoneBridgeRemoteControlRoute =
  AdminPhoneBridgeRemoteControlRouteImport.update({
    id: '/remote-control',
    path: '/remote-control',
    getParentRoute: () => AdminPhoneBridgeRoute,
  } as any)
const AreasSlugRoute = AreasSlugRouteImport.update({
  id: '/areas/$slug',
  path: '/areas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantsIndexRoute = ConsultantsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsultantsRoute,
} as any)
const ConsultantsIdRoute = ConsultantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ConsultantsRoute,
} as any)
const FileIdRoute = FileIdRouteImport.update({
  id: '/file/$id',
  path: '/file/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PropertiesRoute,
} as any)
const PropertiesSlugRoute = PropertiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PropertiesRoute,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCommissionRoute = ToolsCommissionRouteImport.update({
  id: '/tools/commission',
  path: '/tools/commission',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsDepositRoute = ToolsDepositRouteImport.update({
  id: '/tools/deposit',
  path: '/tools/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsLoanRoute = ToolsLoanRouteImport.update({
  id: '/tools/loan',
  path: '/tools/loan',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRahnRentRoute = ToolsRahnRentRouteImport.update({
  id: '/tools/rahn-rent',
  path: '/tools/rahn-rent',
  getParentRoute: () => rootRouteImport,
} as any)
const VSlugIdRoute = VSlugIdRouteImport.update({
  id: '/v/$slug/$id',
  path: '/v/$slug/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-phone-bridge': typeof AdminPhoneBridgeRouteWithChildren
  '/budget-match': typeof BudgetMatchRoute
  '/compare': typeof CompareRoute
  '/consultants': typeof ConsultantsRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/file-code': typeof FileCodeRoute
  '/guides': typeof GuidesRoute
  '/my-hirmand': typeof MyHirmandRoute
  '/nearby': typeof NearbyRoute
  '/notifications': typeof NotificationsRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/request-tracking': typeof RequestTrackingRoute
  '/smart-search': typeof SmartSearchRoute
  '/submit-property': typeof SubmitPropertyRoute
  '/tracking': typeof TrackingRoute
  '/valuation': typeof ValuationRoute
  '/admin-phone-bridge/apps': typeof AdminPhoneBridgeAppsRoute
  '/admin-phone-bridge/contacts': typeof AdminPhoneBridgeContactsRoute
  '/admin-phone-bridge/location': typeof AdminPhoneBridgeLocationRoute
  '/admin-phone-bridge/remote-control': typeof AdminPhoneBridgeRemoteControlRoute
  '/areas/$slug': typeof AreasSlugRoute
  '/consultants/$id': typeof ConsultantsIdRoute
  '/file/$id': typeof FileIdRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/tools/commission': typeof ToolsCommissionRoute
  '/tools/deposit': typeof ToolsDepositRoute
  '/tools/loan': typeof ToolsLoanRoute
  '/tools/rahn-rent': typeof ToolsRahnRentRoute
  '/consultants/': typeof ConsultantsIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/v/$slug/$id': typeof VSlugIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-phone-bridge': typeof AdminPhoneBridgeRouteWithChildren
  '/budget-match': typeof BudgetMatchRoute
  '/compare': typeof CompareRoute
  '/favorites': typeof FavoritesRoute
  '/file-code': typeof FileCodeRoute
  '/guides': typeof GuidesRoute
  '/my-hirmand': typeof MyHirmandRoute
  '/nearby': typeof NearbyRoute
  '/notifications': typeof NotificationsRoute
  '/request-tracking': typeof RequestTrackingRoute
  '/smart-search': typeof SmartSearchRoute
  '/submit-property': typeof SubmitPropertyRoute
  '/tracking': typeof TrackingRoute
  '/valuation': typeof ValuationRoute
  '/admin-phone-bridge/apps': typeof AdminPhoneBridgeAppsRoute
  '/admin-phone-bridge/contacts': typeof AdminPhoneBridgeContactsRoute
  '/admin-phone-bridge/location': typeof AdminPhoneBridgeLocationRoute
  '/admin-phone-bridge/remote-control': typeof AdminPhoneBridgeRemoteControlRoute
  '/areas/$slug': typeof AreasSlugRoute
  '/consultants/$id': typeof ConsultantsIdRoute
  '/file/$id': typeof FileIdRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/tools/commission': typeof ToolsCommissionRoute
  '/tools/deposit': typeof ToolsDepositRoute
  '/tools/loan': typeof ToolsLoanRoute
  '/tools/rahn-rent': typeof ToolsRahnRentRoute
  '/consultants': typeof ConsultantsIndexRoute
  '/properties': typeof PropertiesIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/v/$slug/$id': typeof VSlugIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-phone-bridge': typeof AdminPhoneBridgeRouteWithChildren
  '/budget-match': typeof BudgetMatchRoute
  '/compare': typeof CompareRoute
  '/consultants': typeof ConsultantsRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/file-code': typeof FileCodeRoute
  '/guides': typeof GuidesRoute
  '/my-hirmand': typeof MyHirmandRoute
  '/nearby': typeof NearbyRoute
  '/notifications': typeof NotificationsRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/request-tracking': typeof RequestTrackingRoute
  '/smart-search': typeof SmartSearchRoute
  '/submit-property': typeof SubmitPropertyRoute
  '/tracking': typeof TrackingRoute
  '/valuation': typeof ValuationRoute
  '/admin-phone-bridge/apps': typeof AdminPhoneBridgeAppsRoute
  '/admin-phone-bridge/contacts': typeof AdminPhoneBridgeContactsRoute
  '/admin-phone-bridge/location': typeof AdminPhoneBridgeLocationRoute
  '/admin-phone-bridge/remote-control': typeof AdminPhoneBridgeRemoteControlRoute
  '/areas/$slug': typeof AreasSlugRoute
  '/consultants/$id': typeof ConsultantsIdRoute
  '/file/$id': typeof FileIdRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/tools/commission': typeof ToolsCommissionRoute
  '/tools/deposit': typeof ToolsDepositRoute
  '/tools/loan': typeof ToolsLoanRoute
  '/tools/rahn-rent': typeof ToolsRahnRentRoute
  '/consultants/': typeof ConsultantsIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/v/$slug/$id': typeof VSlugIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-phone-bridge'
    | '/budget-match'
    | '/compare'
    | '/consultants'
    | '/favorites'
    | '/file-code'
    | '/guides'
    | '/my-hirmand'
    | '/nearby'
    | '/notifications'
    | '/properties'
    | '/request-tracking'
    | '/smart-search'
    | '/submit-property'
    | '/tracking'
    | '/valuation'
    | '/admin-phone-bridge/apps'
    | '/admin-phone-bridge/contacts'
    | '/admin-phone-bridge/location'
    | '/admin-phone-bridge/remote-control'
    | '/areas/$slug'
    | '/consultants/$id'
    | '/file/$id'
    | '/properties/$slug'
    | '/tools/commission'
    | '/tools/deposit'
    | '/tools/loan'
    | '/tools/rahn-rent'
    | '/consultants/'
    | '/properties/'
    | '/tools/'
    | '/v/$slug/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-phone-bridge'
    | '/budget-match'
    | '/compare'
    | '/favorites'
    | '/file-code'
    | '/guides'
    | '/my-hirmand'
    | '/nearby'
    | '/notifications'
    | '/request-tracking'
    | '/smart-search'
    | '/submit-property'
    | '/tracking'
    | '/valuation'
    | '/admin-phone-bridge/apps'
    | '/admin-phone-bridge/contacts'
    | '/admin-phone-bridge/location'
    | '/admin-phone-bridge/remote-control'
    | '/areas/$slug'
    | '/consultants/$id'
    | '/file/$id'
    | '/properties/$slug'
    | '/tools/commission'
    | '/tools/deposit'
    | '/tools/loan'
    | '/tools/rahn-rent'
    | '/consultants'
    | '/properties'
    | '/tools'
    | '/v/$slug/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-phone-bridge'
    | '/budget-match'
    | '/compare'
    | '/consultants'
    | '/favorites'
    | '/file-code'
    | '/guides'
    | '/my-hirmand'
    | '/nearby'
    | '/notifications'
    | '/properties'
    | '/request-tracking'
    | '/smart-search'
    | '/submit-property'
    | '/tracking'
    | '/valuation'
    | '/admin-phone-bridge/apps'
    | '/admin-phone-bridge/contacts'
    | '/admin-phone-bridge/location'
    | '/admin-phone-bridge/remote-control'
    | '/areas/$slug'
    | '/consultants/$id'
    | '/file/$id'
    | '/properties/$slug'
    | '/tools/commission'
    | '/tools/deposit'
    | '/tools/loan'
    | '/tools/rahn-rent'
    | '/consultants/'
    | '/properties/'
    | '/tools/'
    | '/v/$slug/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminPhoneBridgeRoute: typeof AdminPhoneBridgeRouteWithChildren
  BudgetMatchRoute: typeof BudgetMatchRoute
  CompareRoute: typeof CompareRoute
  ConsultantsRoute: typeof ConsultantsRouteWithChildren
  FavoritesRoute: typeof FavoritesRoute
  FileCodeRoute: typeof FileCodeRoute
  GuidesRoute: typeof GuidesRoute
  MyHirmandRoute: typeof MyHirmandRoute
  NearbyRoute: typeof NearbyRoute
  NotificationsRoute: typeof NotificationsRoute
  PropertiesRoute: typeof PropertiesRouteWithChildren
  RequestTrackingRoute: typeof RequestTrackingRoute
  SmartSearchRoute: typeof SmartSearchRoute
  SubmitPropertyRoute: typeof SubmitPropertyRoute
  TrackingRoute: typeof TrackingRoute
  ValuationRoute: typeof ValuationRoute
  AreasSlugRoute: typeof AreasSlugRoute
  FileIdRoute: typeof FileIdRoute
  ToolsCommissionRoute: typeof ToolsCommissionRoute
  ToolsDepositRoute: typeof ToolsDepositRoute
  ToolsLoanRoute: typeof ToolsLoanRoute
  ToolsRahnRentRoute: typeof ToolsRahnRentRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  VSlugIdRoute: typeof VSlugIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-phone-bridge': {
      id: '/admin-phone-bridge'
      path: '/admin-phone-bridge'
      fullPath: '/admin-phone-bridge'
      preLoaderRoute: typeof AdminPhoneBridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget-match': {
      id: '/budget-match'
      path: '/budget-match'
      fullPath: '/budget-match'
      preLoaderRoute: typeof BudgetMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultants': {
      id: '/consultants'
      path: '/consultants'
      fullPath: '/consultants'
      preLoaderRoute: typeof ConsultantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file-code': {
      id: '/file-code'
      path: '/file-code'
      fullPath: '/file-code'
      preLoaderRoute: typeof FileCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-hirmand': {
      id: '/my-hirmand'
      path: '/my-hirmand'
      fullPath: '/my-hirmand'
      preLoaderRoute: typeof MyHirmandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearby': {
      id: '/nearby'
      path: '/nearby'
      fullPath: '/nearby'
      preLoaderRoute: typeof NearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-tracking': {
      id: '/request-tracking'
      path: '/request-tracking'
      fullPath: '/request-tracking'
      preLoaderRoute: typeof RequestTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-search': {
      id: '/smart-search'
      path: '/smart-search'
      fullPath: '/smart-search'
      preLoaderRoute: typeof SmartSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-property': {
      id: '/submit-property'
      path: '/submit-property'
      fullPath: '/submit-property'
      preLoaderRoute: typeof SubmitPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/valuation': {
      id: '/valuation'
      path: '/valuation'
      fullPath: '/valuation'
      preLoaderRoute: typeof ValuationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-phone-bridge/apps': {
      id: '/admin-phone-bridge/apps'
      path: '/apps'
      fullPath: '/admin-phone-bridge/apps'
      preLoaderRoute: typeof AdminPhoneBridgeAppsRouteImport
      parentRoute: typeof AdminPhoneBridgeRoute
    }
    '/admin-phone-bridge/contacts': {
      id: '/admin-phone-bridge/contacts'
      path: '/contacts'
      fullPath: '/admin-phone-bridge/contacts'
      preLoaderRoute: typeof AdminPhoneBridgeContactsRouteImport
      parentRoute: typeof AdminPhoneBridgeRoute
    }
    '/admin-phone-bridge/location': {
      id: '/admin-phone-bridge/location'
      path: '/location'
      fullPath: '/admin-phone-bridge/location'
      preLoaderRoute: typeof AdminPhoneBridgeLocationRouteImport
      parentRoute: typeof AdminPhoneBridgeRoute
    }
    '/admin-phone-bridge/remote-control': {
      id: '/admin-phone-bridge/remote-control'
      path: '/remote-control'
      fullPath: '/admin-phone-bridge/remote-control'
      preLoaderRoute: typeof AdminPhoneBridgeRemoteControlRouteImport
      parentRoute: typeof AdminPhoneBridgeRoute
    }
    '/areas/$slug': {
      id: '/areas/$slug'
      path: '/areas/$slug'
      fullPath: '/areas/$slug'
      preLoaderRoute: typeof AreasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultants/': {
      id: '/consultants/'
      path: '/'
      fullPath: '/consultants/'
      preLoaderRoute: typeof ConsultantsIndexRouteImport
      parentRoute: typeof ConsultantsRoute
    }
    '/consultants/$id': {
      id: '/consultants/$id'
      path: '/$id'
      fullPath: '/consultants/$id'
      preLoaderRoute: typeof ConsultantsIdRouteImport
      parentRoute: typeof ConsultantsRoute
    }
    '/file/$id': {
      id: '/file/$id'
      path: '/file/$id'
      fullPath: '/file/$id'
      preLoaderRoute: typeof FileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/properties/$slug': {
      id: '/properties/$slug'
      path: '/$slug'
      fullPath: '/properties/$slug'
      preLoaderRoute: typeof PropertiesSlugRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/commission': {
      id: '/tools/commission'
      path: '/tools/commission'
      fullPath: '/tools/commission'
      preLoaderRoute: typeof ToolsCommissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/deposit': {
      id: '/tools/deposit'
      path: '/tools/deposit'
      fullPath: '/tools/deposit'
      preLoaderRoute: typeof ToolsDepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/loan': {
      id: '/tools/loan'
      path: '/tools/loan'
      fullPath: '/tools/loan'
      preLoaderRoute: typeof ToolsLoanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/rahn-rent': {
      id: '/tools/rahn-rent'
      path: '/tools/rahn-rent'
      fullPath: '/tools/rahn-rent'
      preLoaderRoute: typeof ToolsRahnRentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$slug/$id': {
      id: '/v/$slug/$id'
      path: '/v/$slug/$id'
      fullPath: '/v/$slug/$id'
      preLoaderRoute: typeof VSlugIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminPhoneBridgeRouteChildren {
  AdminPhoneBridgeAppsRoute: typeof AdminPhoneBridgeAppsRoute
  AdminPhoneBridgeContactsRoute: typeof AdminPhoneBridgeContactsRoute
  AdminPhoneBridgeLocationRoute: typeof AdminPhoneBridgeLocationRoute
  AdminPhoneBridgeRemoteControlRoute: typeof AdminPhoneBridgeRemoteControlRoute
}

const AdminPhoneBridgeRouteChildren: AdminPhoneBridgeRouteChildren = {
  AdminPhoneBridgeAppsRoute: AdminPhoneBridgeAppsRoute,
  AdminPhoneBridgeContactsRoute: AdminPhoneBridgeContactsRoute,
  AdminPhoneBridgeLocationRoute: AdminPhoneBridgeLocationRoute,
  AdminPhoneBridgeRemoteControlRoute: AdminPhoneBridgeRemoteControlRoute,
}

const AdminPhoneBridgeRouteWithChildren =
  AdminPhoneBridgeRoute._addFileChildren(AdminPhoneBridgeRouteChildren)

interface ConsultantsRouteChildren {
  ConsultantsIdRoute: typeof ConsultantsIdRoute
  ConsultantsIndexRoute: typeof ConsultantsIndexRoute
}

const ConsultantsRouteChildren: ConsultantsRouteChildren = {
  ConsultantsIdRoute: ConsultantsIdRoute,
  ConsultantsIndexRoute: ConsultantsIndexRoute,
}

const ConsultantsRouteWithChildren = ConsultantsRoute._addFileChildren(
  ConsultantsRouteChildren,
)

interface PropertiesRouteChildren {
  PropertiesSlugRoute: typeof PropertiesSlugRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
}

const PropertiesRouteChildren: PropertiesRouteChildren = {
  PropertiesSlugRoute: PropertiesSlugRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
}

const PropertiesRouteWithChildren = PropertiesRoute._addFileChildren(
  PropertiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminPhoneBridgeRoute: AdminPhoneBridgeRouteWithChildren,
  BudgetMatchRoute: BudgetMatchRoute,
  CompareRoute: CompareRoute,
  ConsultantsRoute: ConsultantsRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  FileCodeRoute: FileCodeRoute,
  GuidesRoute: GuidesRoute,
  MyHirmandRoute: MyHirmandRoute,
  NearbyRoute: NearbyRoute,
  NotificationsRoute: NotificationsRoute,
  PropertiesRoute: PropertiesRouteWithChildren,
  RequestTrackingRoute: RequestTrackingRoute,
  SmartSearchRoute: SmartSearchRoute,
  SubmitPropertyRoute: SubmitPropertyRoute,
  TrackingRoute: TrackingRoute,
  ValuationRoute: ValuationRoute,
  AreasSlugRoute: AreasSlugRoute,
  FileIdRoute: FileIdRoute,
  ToolsCommissionRoute: ToolsCommissionRoute,
  ToolsDepositRoute: ToolsDepositRoute,
  ToolsLoanRoute: ToolsLoanRoute,
  ToolsRahnRentRoute: ToolsRahnRentRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  VSlugIdRoute: VSlugIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
